// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ripple.proto

package protocol;

/**
 * <pre>
 * The status of a node in our cluster
 * </pre>
 *
 * Protobuf type {@code protocol.TMClusterNode}
 */
public final class TMClusterNode extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protocol.TMClusterNode)
    TMClusterNodeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TMClusterNode.newBuilder() to construct.
  private TMClusterNode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TMClusterNode() {
    publicKey_ = "";
    nodeName_ = "";
    address_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TMClusterNode();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TMClusterNode(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            publicKey_ = bs;
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            reportTime_ = input.readUInt32();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            nodeLoad_ = input.readUInt32();
            break;
          }
          case 34: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000008;
            nodeName_ = bs;
            break;
          }
          case 42: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000010;
            address_ = bs;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protocol.Ripple.internal_static_protocol_TMClusterNode_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protocol.Ripple.internal_static_protocol_TMClusterNode_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protocol.TMClusterNode.class, protocol.TMClusterNode.Builder.class);
  }

  private int bitField0_;
  public static final int PUBLICKEY_FIELD_NUMBER = 1;
  private volatile java.lang.Object publicKey_;
  /**
   * <code>required string publicKey = 1;</code>
   * @return Whether the publicKey field is set.
   */
  @java.lang.Override
  public boolean hasPublicKey() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required string publicKey = 1;</code>
   * @return The publicKey.
   */
  @java.lang.Override
  public java.lang.String getPublicKey() {
    java.lang.Object ref = publicKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        publicKey_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string publicKey = 1;</code>
   * @return The bytes for publicKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPublicKeyBytes() {
    java.lang.Object ref = publicKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      publicKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REPORTTIME_FIELD_NUMBER = 2;
  private int reportTime_;
  /**
   * <code>required uint32 reportTime = 2;</code>
   * @return Whether the reportTime field is set.
   */
  @java.lang.Override
  public boolean hasReportTime() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required uint32 reportTime = 2;</code>
   * @return The reportTime.
   */
  @java.lang.Override
  public int getReportTime() {
    return reportTime_;
  }

  public static final int NODELOAD_FIELD_NUMBER = 3;
  private int nodeLoad_;
  /**
   * <code>required uint32 nodeLoad = 3;</code>
   * @return Whether the nodeLoad field is set.
   */
  @java.lang.Override
  public boolean hasNodeLoad() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>required uint32 nodeLoad = 3;</code>
   * @return The nodeLoad.
   */
  @java.lang.Override
  public int getNodeLoad() {
    return nodeLoad_;
  }

  public static final int NODENAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object nodeName_;
  /**
   * <code>optional string nodeName = 4;</code>
   * @return Whether the nodeName field is set.
   */
  @java.lang.Override
  public boolean hasNodeName() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string nodeName = 4;</code>
   * @return The nodeName.
   */
  @java.lang.Override
  public java.lang.String getNodeName() {
    java.lang.Object ref = nodeName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        nodeName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string nodeName = 4;</code>
   * @return The bytes for nodeName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNodeNameBytes() {
    java.lang.Object ref = nodeName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nodeName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDRESS_FIELD_NUMBER = 5;
  private volatile java.lang.Object address_;
  /**
   * <code>optional string address = 5;</code>
   * @return Whether the address field is set.
   */
  @java.lang.Override
  public boolean hasAddress() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional string address = 5;</code>
   * @return The address.
   */
  @java.lang.Override
  public java.lang.String getAddress() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        address_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string address = 5;</code>
   * @return The bytes for address.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAddressBytes() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      address_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasPublicKey()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasReportTime()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasNodeLoad()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, publicKey_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeUInt32(2, reportTime_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeUInt32(3, nodeLoad_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, nodeName_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, address_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, publicKey_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, reportTime_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, nodeLoad_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, nodeName_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, address_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protocol.TMClusterNode)) {
      return super.equals(obj);
    }
    protocol.TMClusterNode other = (protocol.TMClusterNode) obj;

    if (hasPublicKey() != other.hasPublicKey()) return false;
    if (hasPublicKey()) {
      if (!getPublicKey()
          .equals(other.getPublicKey())) return false;
    }
    if (hasReportTime() != other.hasReportTime()) return false;
    if (hasReportTime()) {
      if (getReportTime()
          != other.getReportTime()) return false;
    }
    if (hasNodeLoad() != other.hasNodeLoad()) return false;
    if (hasNodeLoad()) {
      if (getNodeLoad()
          != other.getNodeLoad()) return false;
    }
    if (hasNodeName() != other.hasNodeName()) return false;
    if (hasNodeName()) {
      if (!getNodeName()
          .equals(other.getNodeName())) return false;
    }
    if (hasAddress() != other.hasAddress()) return false;
    if (hasAddress()) {
      if (!getAddress()
          .equals(other.getAddress())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPublicKey()) {
      hash = (37 * hash) + PUBLICKEY_FIELD_NUMBER;
      hash = (53 * hash) + getPublicKey().hashCode();
    }
    if (hasReportTime()) {
      hash = (37 * hash) + REPORTTIME_FIELD_NUMBER;
      hash = (53 * hash) + getReportTime();
    }
    if (hasNodeLoad()) {
      hash = (37 * hash) + NODELOAD_FIELD_NUMBER;
      hash = (53 * hash) + getNodeLoad();
    }
    if (hasNodeName()) {
      hash = (37 * hash) + NODENAME_FIELD_NUMBER;
      hash = (53 * hash) + getNodeName().hashCode();
    }
    if (hasAddress()) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protocol.TMClusterNode parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol.TMClusterNode parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol.TMClusterNode parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol.TMClusterNode parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol.TMClusterNode parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol.TMClusterNode parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol.TMClusterNode parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protocol.TMClusterNode parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protocol.TMClusterNode parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protocol.TMClusterNode parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protocol.TMClusterNode parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protocol.TMClusterNode parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protocol.TMClusterNode prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The status of a node in our cluster
   * </pre>
   *
   * Protobuf type {@code protocol.TMClusterNode}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol.TMClusterNode)
      protocol.TMClusterNodeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Ripple.internal_static_protocol_TMClusterNode_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Ripple.internal_static_protocol_TMClusterNode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.TMClusterNode.class, protocol.TMClusterNode.Builder.class);
    }

    // Construct using protocol.TMClusterNode.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      publicKey_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      reportTime_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      nodeLoad_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      nodeName_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      address_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protocol.Ripple.internal_static_protocol_TMClusterNode_descriptor;
    }

    @java.lang.Override
    public protocol.TMClusterNode getDefaultInstanceForType() {
      return protocol.TMClusterNode.getDefaultInstance();
    }

    @java.lang.Override
    public protocol.TMClusterNode build() {
      protocol.TMClusterNode result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protocol.TMClusterNode buildPartial() {
      protocol.TMClusterNode result = new protocol.TMClusterNode(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.publicKey_ = publicKey_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.reportTime_ = reportTime_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.nodeLoad_ = nodeLoad_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.nodeName_ = nodeName_;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        to_bitField0_ |= 0x00000010;
      }
      result.address_ = address_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protocol.TMClusterNode) {
        return mergeFrom((protocol.TMClusterNode)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protocol.TMClusterNode other) {
      if (other == protocol.TMClusterNode.getDefaultInstance()) return this;
      if (other.hasPublicKey()) {
        bitField0_ |= 0x00000001;
        publicKey_ = other.publicKey_;
        onChanged();
      }
      if (other.hasReportTime()) {
        setReportTime(other.getReportTime());
      }
      if (other.hasNodeLoad()) {
        setNodeLoad(other.getNodeLoad());
      }
      if (other.hasNodeName()) {
        bitField0_ |= 0x00000008;
        nodeName_ = other.nodeName_;
        onChanged();
      }
      if (other.hasAddress()) {
        bitField0_ |= 0x00000010;
        address_ = other.address_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasPublicKey()) {
        return false;
      }
      if (!hasReportTime()) {
        return false;
      }
      if (!hasNodeLoad()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protocol.TMClusterNode parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protocol.TMClusterNode) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object publicKey_ = "";
    /**
     * <code>required string publicKey = 1;</code>
     * @return Whether the publicKey field is set.
     */
    public boolean hasPublicKey() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string publicKey = 1;</code>
     * @return The publicKey.
     */
    public java.lang.String getPublicKey() {
      java.lang.Object ref = publicKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          publicKey_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string publicKey = 1;</code>
     * @return The bytes for publicKey.
     */
    public com.google.protobuf.ByteString
        getPublicKeyBytes() {
      java.lang.Object ref = publicKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        publicKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string publicKey = 1;</code>
     * @param value The publicKey to set.
     * @return This builder for chaining.
     */
    public Builder setPublicKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      publicKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string publicKey = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPublicKey() {
      bitField0_ = (bitField0_ & ~0x00000001);
      publicKey_ = getDefaultInstance().getPublicKey();
      onChanged();
      return this;
    }
    /**
     * <code>required string publicKey = 1;</code>
     * @param value The bytes for publicKey to set.
     * @return This builder for chaining.
     */
    public Builder setPublicKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      publicKey_ = value;
      onChanged();
      return this;
    }

    private int reportTime_ ;
    /**
     * <code>required uint32 reportTime = 2;</code>
     * @return Whether the reportTime field is set.
     */
    @java.lang.Override
    public boolean hasReportTime() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required uint32 reportTime = 2;</code>
     * @return The reportTime.
     */
    @java.lang.Override
    public int getReportTime() {
      return reportTime_;
    }
    /**
     * <code>required uint32 reportTime = 2;</code>
     * @param value The reportTime to set.
     * @return This builder for chaining.
     */
    public Builder setReportTime(int value) {
      bitField0_ |= 0x00000002;
      reportTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required uint32 reportTime = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearReportTime() {
      bitField0_ = (bitField0_ & ~0x00000002);
      reportTime_ = 0;
      onChanged();
      return this;
    }

    private int nodeLoad_ ;
    /**
     * <code>required uint32 nodeLoad = 3;</code>
     * @return Whether the nodeLoad field is set.
     */
    @java.lang.Override
    public boolean hasNodeLoad() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required uint32 nodeLoad = 3;</code>
     * @return The nodeLoad.
     */
    @java.lang.Override
    public int getNodeLoad() {
      return nodeLoad_;
    }
    /**
     * <code>required uint32 nodeLoad = 3;</code>
     * @param value The nodeLoad to set.
     * @return This builder for chaining.
     */
    public Builder setNodeLoad(int value) {
      bitField0_ |= 0x00000004;
      nodeLoad_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required uint32 nodeLoad = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNodeLoad() {
      bitField0_ = (bitField0_ & ~0x00000004);
      nodeLoad_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object nodeName_ = "";
    /**
     * <code>optional string nodeName = 4;</code>
     * @return Whether the nodeName field is set.
     */
    public boolean hasNodeName() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string nodeName = 4;</code>
     * @return The nodeName.
     */
    public java.lang.String getNodeName() {
      java.lang.Object ref = nodeName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nodeName_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string nodeName = 4;</code>
     * @return The bytes for nodeName.
     */
    public com.google.protobuf.ByteString
        getNodeNameBytes() {
      java.lang.Object ref = nodeName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string nodeName = 4;</code>
     * @param value The nodeName to set.
     * @return This builder for chaining.
     */
    public Builder setNodeName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      nodeName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string nodeName = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearNodeName() {
      bitField0_ = (bitField0_ & ~0x00000008);
      nodeName_ = getDefaultInstance().getNodeName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string nodeName = 4;</code>
     * @param value The bytes for nodeName to set.
     * @return This builder for chaining.
     */
    public Builder setNodeNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      nodeName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object address_ = "";
    /**
     * <code>optional string address = 5;</code>
     * @return Whether the address field is set.
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string address = 5;</code>
     * @return The address.
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          address_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string address = 5;</code>
     * @return The bytes for address.
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string address = 5;</code>
     * @param value The address to set.
     * @return This builder for chaining.
     */
    public Builder setAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      address_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string address = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddress() {
      bitField0_ = (bitField0_ & ~0x00000010);
      address_ = getDefaultInstance().getAddress();
      onChanged();
      return this;
    }
    /**
     * <code>optional string address = 5;</code>
     * @param value The bytes for address to set.
     * @return This builder for chaining.
     */
    public Builder setAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      address_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protocol.TMClusterNode)
  }

  // @@protoc_insertion_point(class_scope:protocol.TMClusterNode)
  private static final protocol.TMClusterNode DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protocol.TMClusterNode();
  }

  public static protocol.TMClusterNode getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<TMClusterNode>
      PARSER = new com.google.protobuf.AbstractParser<TMClusterNode>() {
    @java.lang.Override
    public TMClusterNode parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TMClusterNode(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TMClusterNode> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TMClusterNode> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protocol.TMClusterNode getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

