// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ripple.proto

package protocol;

/**
 * <pre>
 * Request info on shards held
 * </pre>
 *
 * Protobuf type {@code protocol.TMGetShardInfo}
 */
public final class TMGetShardInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protocol.TMGetShardInfo)
    TMGetShardInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TMGetShardInfo.newBuilder() to construct.
  private TMGetShardInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TMGetShardInfo() {
    peerchain_ = emptyIntList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TMGetShardInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TMGetShardInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            hops_ = input.readUInt32();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            lastLink_ = input.readBool();
            break;
          }
          case 24: {
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              peerchain_ = newIntList();
              mutable_bitField0_ |= 0x00000004;
            }
            peerchain_.addInt(input.readUInt32());
            break;
          }
          case 26: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000004) != 0) && input.getBytesUntilLimit() > 0) {
              peerchain_ = newIntList();
              mutable_bitField0_ |= 0x00000004;
            }
            while (input.getBytesUntilLimit() > 0) {
              peerchain_.addInt(input.readUInt32());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        peerchain_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protocol.Ripple.internal_static_protocol_TMGetShardInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protocol.Ripple.internal_static_protocol_TMGetShardInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protocol.TMGetShardInfo.class, protocol.TMGetShardInfo.Builder.class);
  }

  private int bitField0_;
  public static final int HOPS_FIELD_NUMBER = 1;
  private int hops_;
  /**
   * <pre>
   * number of hops to travel
   * </pre>
   *
   * <code>required uint32 hops = 1 [deprecated = true];</code>
   * @return Whether the hops field is set.
   */
  @java.lang.Override
  @java.lang.Deprecated public boolean hasHops() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * number of hops to travel
   * </pre>
   *
   * <code>required uint32 hops = 1 [deprecated = true];</code>
   * @return The hops.
   */
  @java.lang.Override
  @java.lang.Deprecated public int getHops() {
    return hops_;
  }

  public static final int LASTLINK_FIELD_NUMBER = 2;
  private boolean lastLink_;
  /**
   * <pre>
   * true if last link in the peer chain
   * </pre>
   *
   * <code>optional bool lastLink = 2 [deprecated = true];</code>
   * @return Whether the lastLink field is set.
   */
  @java.lang.Override
  @java.lang.Deprecated public boolean hasLastLink() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * true if last link in the peer chain
   * </pre>
   *
   * <code>optional bool lastLink = 2 [deprecated = true];</code>
   * @return The lastLink.
   */
  @java.lang.Override
  @java.lang.Deprecated public boolean getLastLink() {
    return lastLink_;
  }

  public static final int PEERCHAIN_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.IntList peerchain_;
  /**
   * <pre>
   * IDs used to route messages
   * </pre>
   *
   * <code>repeated uint32 peerchain = 3 [deprecated = true];</code>
   * @return A list containing the peerchain.
   */
  @java.lang.Override
  @java.lang.Deprecated public java.util.List<java.lang.Integer>
      getPeerchainList() {
    return peerchain_;
  }
  /**
   * <pre>
   * IDs used to route messages
   * </pre>
   *
   * <code>repeated uint32 peerchain = 3 [deprecated = true];</code>
   * @return The count of peerchain.
   */
  @java.lang.Deprecated public int getPeerchainCount() {
    return peerchain_.size();
  }
  /**
   * <pre>
   * IDs used to route messages
   * </pre>
   *
   * <code>repeated uint32 peerchain = 3 [deprecated = true];</code>
   * @param index The index of the element to return.
   * @return The peerchain at the given index.
   */
  @java.lang.Deprecated public int getPeerchain(int index) {
    return peerchain_.getInt(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasHops()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeUInt32(1, hops_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeBool(2, lastLink_);
    }
    for (int i = 0; i < peerchain_.size(); i++) {
      output.writeUInt32(3, peerchain_.getInt(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, hops_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, lastLink_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < peerchain_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(peerchain_.getInt(i));
      }
      size += dataSize;
      size += 1 * getPeerchainList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protocol.TMGetShardInfo)) {
      return super.equals(obj);
    }
    protocol.TMGetShardInfo other = (protocol.TMGetShardInfo) obj;

    if (hasHops() != other.hasHops()) return false;
    if (hasHops()) {
      if (getHops()
          != other.getHops()) return false;
    }
    if (hasLastLink() != other.hasLastLink()) return false;
    if (hasLastLink()) {
      if (getLastLink()
          != other.getLastLink()) return false;
    }
    if (!getPeerchainList()
        .equals(other.getPeerchainList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHops()) {
      hash = (37 * hash) + HOPS_FIELD_NUMBER;
      hash = (53 * hash) + getHops();
    }
    if (hasLastLink()) {
      hash = (37 * hash) + LASTLINK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getLastLink());
    }
    if (getPeerchainCount() > 0) {
      hash = (37 * hash) + PEERCHAIN_FIELD_NUMBER;
      hash = (53 * hash) + getPeerchainList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protocol.TMGetShardInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol.TMGetShardInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol.TMGetShardInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol.TMGetShardInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol.TMGetShardInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol.TMGetShardInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol.TMGetShardInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protocol.TMGetShardInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protocol.TMGetShardInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protocol.TMGetShardInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protocol.TMGetShardInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protocol.TMGetShardInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protocol.TMGetShardInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Request info on shards held
   * </pre>
   *
   * Protobuf type {@code protocol.TMGetShardInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol.TMGetShardInfo)
      protocol.TMGetShardInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Ripple.internal_static_protocol_TMGetShardInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Ripple.internal_static_protocol_TMGetShardInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.TMGetShardInfo.class, protocol.TMGetShardInfo.Builder.class);
    }

    // Construct using protocol.TMGetShardInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      hops_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      lastLink_ = false;
      bitField0_ = (bitField0_ & ~0x00000002);
      peerchain_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protocol.Ripple.internal_static_protocol_TMGetShardInfo_descriptor;
    }

    @java.lang.Override
    public protocol.TMGetShardInfo getDefaultInstanceForType() {
      return protocol.TMGetShardInfo.getDefaultInstance();
    }

    @java.lang.Override
    public protocol.TMGetShardInfo build() {
      protocol.TMGetShardInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protocol.TMGetShardInfo buildPartial() {
      protocol.TMGetShardInfo result = new protocol.TMGetShardInfo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.hops_ = hops_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.lastLink_ = lastLink_;
        to_bitField0_ |= 0x00000002;
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        peerchain_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.peerchain_ = peerchain_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protocol.TMGetShardInfo) {
        return mergeFrom((protocol.TMGetShardInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protocol.TMGetShardInfo other) {
      if (other == protocol.TMGetShardInfo.getDefaultInstance()) return this;
      if (other.hasHops()) {
        setHops(other.getHops());
      }
      if (other.hasLastLink()) {
        setLastLink(other.getLastLink());
      }
      if (!other.peerchain_.isEmpty()) {
        if (peerchain_.isEmpty()) {
          peerchain_ = other.peerchain_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensurePeerchainIsMutable();
          peerchain_.addAll(other.peerchain_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasHops()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protocol.TMGetShardInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protocol.TMGetShardInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int hops_ ;
    /**
     * <pre>
     * number of hops to travel
     * </pre>
     *
     * <code>required uint32 hops = 1 [deprecated = true];</code>
     * @return Whether the hops field is set.
     */
    @java.lang.Override
    @java.lang.Deprecated public boolean hasHops() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * number of hops to travel
     * </pre>
     *
     * <code>required uint32 hops = 1 [deprecated = true];</code>
     * @return The hops.
     */
    @java.lang.Override
    @java.lang.Deprecated public int getHops() {
      return hops_;
    }
    /**
     * <pre>
     * number of hops to travel
     * </pre>
     *
     * <code>required uint32 hops = 1 [deprecated = true];</code>
     * @param value The hops to set.
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder setHops(int value) {
      bitField0_ |= 0x00000001;
      hops_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * number of hops to travel
     * </pre>
     *
     * <code>required uint32 hops = 1 [deprecated = true];</code>
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder clearHops() {
      bitField0_ = (bitField0_ & ~0x00000001);
      hops_ = 0;
      onChanged();
      return this;
    }

    private boolean lastLink_ ;
    /**
     * <pre>
     * true if last link in the peer chain
     * </pre>
     *
     * <code>optional bool lastLink = 2 [deprecated = true];</code>
     * @return Whether the lastLink field is set.
     */
    @java.lang.Override
    @java.lang.Deprecated public boolean hasLastLink() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * true if last link in the peer chain
     * </pre>
     *
     * <code>optional bool lastLink = 2 [deprecated = true];</code>
     * @return The lastLink.
     */
    @java.lang.Override
    @java.lang.Deprecated public boolean getLastLink() {
      return lastLink_;
    }
    /**
     * <pre>
     * true if last link in the peer chain
     * </pre>
     *
     * <code>optional bool lastLink = 2 [deprecated = true];</code>
     * @param value The lastLink to set.
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder setLastLink(boolean value) {
      bitField0_ |= 0x00000002;
      lastLink_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * true if last link in the peer chain
     * </pre>
     *
     * <code>optional bool lastLink = 2 [deprecated = true];</code>
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder clearLastLink() {
      bitField0_ = (bitField0_ & ~0x00000002);
      lastLink_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList peerchain_ = emptyIntList();
    private void ensurePeerchainIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        peerchain_ = mutableCopy(peerchain_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <pre>
     * IDs used to route messages
     * </pre>
     *
     * <code>repeated uint32 peerchain = 3 [deprecated = true];</code>
     * @return A list containing the peerchain.
     */
    @java.lang.Deprecated public java.util.List<java.lang.Integer>
        getPeerchainList() {
      return ((bitField0_ & 0x00000004) != 0) ?
               java.util.Collections.unmodifiableList(peerchain_) : peerchain_;
    }
    /**
     * <pre>
     * IDs used to route messages
     * </pre>
     *
     * <code>repeated uint32 peerchain = 3 [deprecated = true];</code>
     * @return The count of peerchain.
     */
    @java.lang.Deprecated public int getPeerchainCount() {
      return peerchain_.size();
    }
    /**
     * <pre>
     * IDs used to route messages
     * </pre>
     *
     * <code>repeated uint32 peerchain = 3 [deprecated = true];</code>
     * @param index The index of the element to return.
     * @return The peerchain at the given index.
     */
    @java.lang.Deprecated public int getPeerchain(int index) {
      return peerchain_.getInt(index);
    }
    /**
     * <pre>
     * IDs used to route messages
     * </pre>
     *
     * <code>repeated uint32 peerchain = 3 [deprecated = true];</code>
     * @param index The index to set the value at.
     * @param value The peerchain to set.
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder setPeerchain(
        int index, int value) {
      ensurePeerchainIsMutable();
      peerchain_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * IDs used to route messages
     * </pre>
     *
     * <code>repeated uint32 peerchain = 3 [deprecated = true];</code>
     * @param value The peerchain to add.
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder addPeerchain(int value) {
      ensurePeerchainIsMutable();
      peerchain_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * IDs used to route messages
     * </pre>
     *
     * <code>repeated uint32 peerchain = 3 [deprecated = true];</code>
     * @param values The peerchain to add.
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder addAllPeerchain(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensurePeerchainIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, peerchain_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * IDs used to route messages
     * </pre>
     *
     * <code>repeated uint32 peerchain = 3 [deprecated = true];</code>
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder clearPeerchain() {
      peerchain_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protocol.TMGetShardInfo)
  }

  // @@protoc_insertion_point(class_scope:protocol.TMGetShardInfo)
  private static final protocol.TMGetShardInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protocol.TMGetShardInfo();
  }

  public static protocol.TMGetShardInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<TMGetShardInfo>
      PARSER = new com.google.protobuf.AbstractParser<TMGetShardInfo>() {
    @java.lang.Override
    public TMGetShardInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TMGetShardInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TMGetShardInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TMGetShardInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protocol.TMGetShardInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

