// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ripple.proto

package protocol;

/**
 * Protobuf type {@code protocol.TMGetLedger}
 */
public final class TMGetLedger extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protocol.TMGetLedger)
    TMGetLedgerOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TMGetLedger.newBuilder() to construct.
  private TMGetLedger(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TMGetLedger() {
    itype_ = 0;
    ltype_ = 0;
    ledgerHash_ = com.google.protobuf.ByteString.EMPTY;
    nodeIDs_ = java.util.Collections.emptyList();
    queryType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TMGetLedger();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TMGetLedger(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();
              @SuppressWarnings("deprecation")
            protocol.TMLedgerInfoType value = protocol.TMLedgerInfoType.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(1, rawValue);
            } else {
              bitField0_ |= 0x00000001;
              itype_ = rawValue;
            }
            break;
          }
          case 16: {
            int rawValue = input.readEnum();
              @SuppressWarnings("deprecation")
            protocol.TMLedgerType value = protocol.TMLedgerType.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(2, rawValue);
            } else {
              bitField0_ |= 0x00000002;
              ltype_ = rawValue;
            }
            break;
          }
          case 26: {
            bitField0_ |= 0x00000004;
            ledgerHash_ = input.readBytes();
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            ledgerSeq_ = input.readUInt32();
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) != 0)) {
              nodeIDs_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
              mutable_bitField0_ |= 0x00000010;
            }
            nodeIDs_.add(input.readBytes());
            break;
          }
          case 48: {
            bitField0_ |= 0x00000010;
            requestCookie_ = input.readUInt64();
            break;
          }
          case 56: {
            int rawValue = input.readEnum();
              @SuppressWarnings("deprecation")
            protocol.TMQueryType value = protocol.TMQueryType.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(7, rawValue);
            } else {
              bitField0_ |= 0x00000020;
              queryType_ = rawValue;
            }
            break;
          }
          case 64: {
            bitField0_ |= 0x00000040;
            queryDepth_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) != 0)) {
        nodeIDs_ = java.util.Collections.unmodifiableList(nodeIDs_); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protocol.Ripple.internal_static_protocol_TMGetLedger_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protocol.Ripple.internal_static_protocol_TMGetLedger_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protocol.TMGetLedger.class, protocol.TMGetLedger.Builder.class);
  }

  private int bitField0_;
  public static final int ITYPE_FIELD_NUMBER = 1;
  private int itype_;
  /**
   * <code>required .protocol.TMLedgerInfoType itype = 1;</code>
   * @return Whether the itype field is set.
   */
  @java.lang.Override public boolean hasItype() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required .protocol.TMLedgerInfoType itype = 1;</code>
   * @return The itype.
   */
  @java.lang.Override public protocol.TMLedgerInfoType getItype() {
    @SuppressWarnings("deprecation")
    protocol.TMLedgerInfoType result = protocol.TMLedgerInfoType.valueOf(itype_);
    return result == null ? protocol.TMLedgerInfoType.liBASE : result;
  }

  public static final int LTYPE_FIELD_NUMBER = 2;
  private int ltype_;
  /**
   * <code>optional .protocol.TMLedgerType ltype = 2;</code>
   * @return Whether the ltype field is set.
   */
  @java.lang.Override public boolean hasLtype() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .protocol.TMLedgerType ltype = 2;</code>
   * @return The ltype.
   */
  @java.lang.Override public protocol.TMLedgerType getLtype() {
    @SuppressWarnings("deprecation")
    protocol.TMLedgerType result = protocol.TMLedgerType.valueOf(ltype_);
    return result == null ? protocol.TMLedgerType.ltACCEPTED : result;
  }

  public static final int LEDGERHASH_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString ledgerHash_;
  /**
   * <pre>
   * Can also be the transaction set hash if liTS_CANDIDATE
   * </pre>
   *
   * <code>optional bytes ledgerHash = 3;</code>
   * @return Whether the ledgerHash field is set.
   */
  @java.lang.Override
  public boolean hasLedgerHash() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * Can also be the transaction set hash if liTS_CANDIDATE
   * </pre>
   *
   * <code>optional bytes ledgerHash = 3;</code>
   * @return The ledgerHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getLedgerHash() {
    return ledgerHash_;
  }

  public static final int LEDGERSEQ_FIELD_NUMBER = 4;
  private int ledgerSeq_;
  /**
   * <code>optional uint32 ledgerSeq = 4;</code>
   * @return Whether the ledgerSeq field is set.
   */
  @java.lang.Override
  public boolean hasLedgerSeq() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional uint32 ledgerSeq = 4;</code>
   * @return The ledgerSeq.
   */
  @java.lang.Override
  public int getLedgerSeq() {
    return ledgerSeq_;
  }

  public static final int NODEIDS_FIELD_NUMBER = 5;
  private java.util.List<com.google.protobuf.ByteString> nodeIDs_;
  /**
   * <code>repeated bytes nodeIDs = 5;</code>
   * @return A list containing the nodeIDs.
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.ByteString>
      getNodeIDsList() {
    return nodeIDs_;
  }
  /**
   * <code>repeated bytes nodeIDs = 5;</code>
   * @return The count of nodeIDs.
   */
  public int getNodeIDsCount() {
    return nodeIDs_.size();
  }
  /**
   * <code>repeated bytes nodeIDs = 5;</code>
   * @param index The index of the element to return.
   * @return The nodeIDs at the given index.
   */
  public com.google.protobuf.ByteString getNodeIDs(int index) {
    return nodeIDs_.get(index);
  }

  public static final int REQUESTCOOKIE_FIELD_NUMBER = 6;
  private long requestCookie_;
  /**
   * <code>optional uint64 requestCookie = 6;</code>
   * @return Whether the requestCookie field is set.
   */
  @java.lang.Override
  public boolean hasRequestCookie() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional uint64 requestCookie = 6;</code>
   * @return The requestCookie.
   */
  @java.lang.Override
  public long getRequestCookie() {
    return requestCookie_;
  }

  public static final int QUERYTYPE_FIELD_NUMBER = 7;
  private int queryType_;
  /**
   * <code>optional .protocol.TMQueryType queryType = 7;</code>
   * @return Whether the queryType field is set.
   */
  @java.lang.Override public boolean hasQueryType() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional .protocol.TMQueryType queryType = 7;</code>
   * @return The queryType.
   */
  @java.lang.Override public protocol.TMQueryType getQueryType() {
    @SuppressWarnings("deprecation")
    protocol.TMQueryType result = protocol.TMQueryType.valueOf(queryType_);
    return result == null ? protocol.TMQueryType.qtINDIRECT : result;
  }

  public static final int QUERYDEPTH_FIELD_NUMBER = 8;
  private int queryDepth_;
  /**
   * <pre>
   * How deep to go, number of extra levels
   * </pre>
   *
   * <code>optional uint32 queryDepth = 8;</code>
   * @return Whether the queryDepth field is set.
   */
  @java.lang.Override
  public boolean hasQueryDepth() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <pre>
   * How deep to go, number of extra levels
   * </pre>
   *
   * <code>optional uint32 queryDepth = 8;</code>
   * @return The queryDepth.
   */
  @java.lang.Override
  public int getQueryDepth() {
    return queryDepth_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasItype()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeEnum(1, itype_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeEnum(2, ltype_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeBytes(3, ledgerHash_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeUInt32(4, ledgerSeq_);
    }
    for (int i = 0; i < nodeIDs_.size(); i++) {
      output.writeBytes(5, nodeIDs_.get(i));
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeUInt64(6, requestCookie_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeEnum(7, queryType_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeUInt32(8, queryDepth_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, itype_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, ltype_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, ledgerHash_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, ledgerSeq_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < nodeIDs_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(nodeIDs_.get(i));
      }
      size += dataSize;
      size += 1 * getNodeIDsList().size();
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(6, requestCookie_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, queryType_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(8, queryDepth_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protocol.TMGetLedger)) {
      return super.equals(obj);
    }
    protocol.TMGetLedger other = (protocol.TMGetLedger) obj;

    if (hasItype() != other.hasItype()) return false;
    if (hasItype()) {
      if (itype_ != other.itype_) return false;
    }
    if (hasLtype() != other.hasLtype()) return false;
    if (hasLtype()) {
      if (ltype_ != other.ltype_) return false;
    }
    if (hasLedgerHash() != other.hasLedgerHash()) return false;
    if (hasLedgerHash()) {
      if (!getLedgerHash()
          .equals(other.getLedgerHash())) return false;
    }
    if (hasLedgerSeq() != other.hasLedgerSeq()) return false;
    if (hasLedgerSeq()) {
      if (getLedgerSeq()
          != other.getLedgerSeq()) return false;
    }
    if (!getNodeIDsList()
        .equals(other.getNodeIDsList())) return false;
    if (hasRequestCookie() != other.hasRequestCookie()) return false;
    if (hasRequestCookie()) {
      if (getRequestCookie()
          != other.getRequestCookie()) return false;
    }
    if (hasQueryType() != other.hasQueryType()) return false;
    if (hasQueryType()) {
      if (queryType_ != other.queryType_) return false;
    }
    if (hasQueryDepth() != other.hasQueryDepth()) return false;
    if (hasQueryDepth()) {
      if (getQueryDepth()
          != other.getQueryDepth()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasItype()) {
      hash = (37 * hash) + ITYPE_FIELD_NUMBER;
      hash = (53 * hash) + itype_;
    }
    if (hasLtype()) {
      hash = (37 * hash) + LTYPE_FIELD_NUMBER;
      hash = (53 * hash) + ltype_;
    }
    if (hasLedgerHash()) {
      hash = (37 * hash) + LEDGERHASH_FIELD_NUMBER;
      hash = (53 * hash) + getLedgerHash().hashCode();
    }
    if (hasLedgerSeq()) {
      hash = (37 * hash) + LEDGERSEQ_FIELD_NUMBER;
      hash = (53 * hash) + getLedgerSeq();
    }
    if (getNodeIDsCount() > 0) {
      hash = (37 * hash) + NODEIDS_FIELD_NUMBER;
      hash = (53 * hash) + getNodeIDsList().hashCode();
    }
    if (hasRequestCookie()) {
      hash = (37 * hash) + REQUESTCOOKIE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRequestCookie());
    }
    if (hasQueryType()) {
      hash = (37 * hash) + QUERYTYPE_FIELD_NUMBER;
      hash = (53 * hash) + queryType_;
    }
    if (hasQueryDepth()) {
      hash = (37 * hash) + QUERYDEPTH_FIELD_NUMBER;
      hash = (53 * hash) + getQueryDepth();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protocol.TMGetLedger parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol.TMGetLedger parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol.TMGetLedger parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol.TMGetLedger parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol.TMGetLedger parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol.TMGetLedger parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol.TMGetLedger parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protocol.TMGetLedger parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protocol.TMGetLedger parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protocol.TMGetLedger parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protocol.TMGetLedger parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protocol.TMGetLedger parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protocol.TMGetLedger prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protocol.TMGetLedger}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol.TMGetLedger)
      protocol.TMGetLedgerOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Ripple.internal_static_protocol_TMGetLedger_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Ripple.internal_static_protocol_TMGetLedger_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.TMGetLedger.class, protocol.TMGetLedger.Builder.class);
    }

    // Construct using protocol.TMGetLedger.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      itype_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      ltype_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      ledgerHash_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      ledgerSeq_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      nodeIDs_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000010);
      requestCookie_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000020);
      queryType_ = 0;
      bitField0_ = (bitField0_ & ~0x00000040);
      queryDepth_ = 0;
      bitField0_ = (bitField0_ & ~0x00000080);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protocol.Ripple.internal_static_protocol_TMGetLedger_descriptor;
    }

    @java.lang.Override
    public protocol.TMGetLedger getDefaultInstanceForType() {
      return protocol.TMGetLedger.getDefaultInstance();
    }

    @java.lang.Override
    public protocol.TMGetLedger build() {
      protocol.TMGetLedger result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protocol.TMGetLedger buildPartial() {
      protocol.TMGetLedger result = new protocol.TMGetLedger(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.itype_ = itype_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.ltype_ = ltype_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.ledgerHash_ = ledgerHash_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.ledgerSeq_ = ledgerSeq_;
        to_bitField0_ |= 0x00000008;
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        nodeIDs_ = java.util.Collections.unmodifiableList(nodeIDs_);
        bitField0_ = (bitField0_ & ~0x00000010);
      }
      result.nodeIDs_ = nodeIDs_;
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.requestCookie_ = requestCookie_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        to_bitField0_ |= 0x00000020;
      }
      result.queryType_ = queryType_;
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.queryDepth_ = queryDepth_;
        to_bitField0_ |= 0x00000040;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protocol.TMGetLedger) {
        return mergeFrom((protocol.TMGetLedger)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protocol.TMGetLedger other) {
      if (other == protocol.TMGetLedger.getDefaultInstance()) return this;
      if (other.hasItype()) {
        setItype(other.getItype());
      }
      if (other.hasLtype()) {
        setLtype(other.getLtype());
      }
      if (other.hasLedgerHash()) {
        setLedgerHash(other.getLedgerHash());
      }
      if (other.hasLedgerSeq()) {
        setLedgerSeq(other.getLedgerSeq());
      }
      if (!other.nodeIDs_.isEmpty()) {
        if (nodeIDs_.isEmpty()) {
          nodeIDs_ = other.nodeIDs_;
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          ensureNodeIDsIsMutable();
          nodeIDs_.addAll(other.nodeIDs_);
        }
        onChanged();
      }
      if (other.hasRequestCookie()) {
        setRequestCookie(other.getRequestCookie());
      }
      if (other.hasQueryType()) {
        setQueryType(other.getQueryType());
      }
      if (other.hasQueryDepth()) {
        setQueryDepth(other.getQueryDepth());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasItype()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protocol.TMGetLedger parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protocol.TMGetLedger) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int itype_ = 0;
    /**
     * <code>required .protocol.TMLedgerInfoType itype = 1;</code>
     * @return Whether the itype field is set.
     */
    @java.lang.Override public boolean hasItype() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .protocol.TMLedgerInfoType itype = 1;</code>
     * @return The itype.
     */
    @java.lang.Override
    public protocol.TMLedgerInfoType getItype() {
      @SuppressWarnings("deprecation")
      protocol.TMLedgerInfoType result = protocol.TMLedgerInfoType.valueOf(itype_);
      return result == null ? protocol.TMLedgerInfoType.liBASE : result;
    }
    /**
     * <code>required .protocol.TMLedgerInfoType itype = 1;</code>
     * @param value The itype to set.
     * @return This builder for chaining.
     */
    public Builder setItype(protocol.TMLedgerInfoType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      itype_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>required .protocol.TMLedgerInfoType itype = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearItype() {
      bitField0_ = (bitField0_ & ~0x00000001);
      itype_ = 0;
      onChanged();
      return this;
    }

    private int ltype_ = 0;
    /**
     * <code>optional .protocol.TMLedgerType ltype = 2;</code>
     * @return Whether the ltype field is set.
     */
    @java.lang.Override public boolean hasLtype() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .protocol.TMLedgerType ltype = 2;</code>
     * @return The ltype.
     */
    @java.lang.Override
    public protocol.TMLedgerType getLtype() {
      @SuppressWarnings("deprecation")
      protocol.TMLedgerType result = protocol.TMLedgerType.valueOf(ltype_);
      return result == null ? protocol.TMLedgerType.ltACCEPTED : result;
    }
    /**
     * <code>optional .protocol.TMLedgerType ltype = 2;</code>
     * @param value The ltype to set.
     * @return This builder for chaining.
     */
    public Builder setLtype(protocol.TMLedgerType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      ltype_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .protocol.TMLedgerType ltype = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLtype() {
      bitField0_ = (bitField0_ & ~0x00000002);
      ltype_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString ledgerHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Can also be the transaction set hash if liTS_CANDIDATE
     * </pre>
     *
     * <code>optional bytes ledgerHash = 3;</code>
     * @return Whether the ledgerHash field is set.
     */
    @java.lang.Override
    public boolean hasLedgerHash() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Can also be the transaction set hash if liTS_CANDIDATE
     * </pre>
     *
     * <code>optional bytes ledgerHash = 3;</code>
     * @return The ledgerHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getLedgerHash() {
      return ledgerHash_;
    }
    /**
     * <pre>
     * Can also be the transaction set hash if liTS_CANDIDATE
     * </pre>
     *
     * <code>optional bytes ledgerHash = 3;</code>
     * @param value The ledgerHash to set.
     * @return This builder for chaining.
     */
    public Builder setLedgerHash(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      ledgerHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Can also be the transaction set hash if liTS_CANDIDATE
     * </pre>
     *
     * <code>optional bytes ledgerHash = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLedgerHash() {
      bitField0_ = (bitField0_ & ~0x00000004);
      ledgerHash_ = getDefaultInstance().getLedgerHash();
      onChanged();
      return this;
    }

    private int ledgerSeq_ ;
    /**
     * <code>optional uint32 ledgerSeq = 4;</code>
     * @return Whether the ledgerSeq field is set.
     */
    @java.lang.Override
    public boolean hasLedgerSeq() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional uint32 ledgerSeq = 4;</code>
     * @return The ledgerSeq.
     */
    @java.lang.Override
    public int getLedgerSeq() {
      return ledgerSeq_;
    }
    /**
     * <code>optional uint32 ledgerSeq = 4;</code>
     * @param value The ledgerSeq to set.
     * @return This builder for chaining.
     */
    public Builder setLedgerSeq(int value) {
      bitField0_ |= 0x00000008;
      ledgerSeq_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 ledgerSeq = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLedgerSeq() {
      bitField0_ = (bitField0_ & ~0x00000008);
      ledgerSeq_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.google.protobuf.ByteString> nodeIDs_ = java.util.Collections.emptyList();
    private void ensureNodeIDsIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        nodeIDs_ = new java.util.ArrayList<com.google.protobuf.ByteString>(nodeIDs_);
        bitField0_ |= 0x00000010;
       }
    }
    /**
     * <code>repeated bytes nodeIDs = 5;</code>
     * @return A list containing the nodeIDs.
     */
    public java.util.List<com.google.protobuf.ByteString>
        getNodeIDsList() {
      return ((bitField0_ & 0x00000010) != 0) ?
               java.util.Collections.unmodifiableList(nodeIDs_) : nodeIDs_;
    }
    /**
     * <code>repeated bytes nodeIDs = 5;</code>
     * @return The count of nodeIDs.
     */
    public int getNodeIDsCount() {
      return nodeIDs_.size();
    }
    /**
     * <code>repeated bytes nodeIDs = 5;</code>
     * @param index The index of the element to return.
     * @return The nodeIDs at the given index.
     */
    public com.google.protobuf.ByteString getNodeIDs(int index) {
      return nodeIDs_.get(index);
    }
    /**
     * <code>repeated bytes nodeIDs = 5;</code>
     * @param index The index to set the value at.
     * @param value The nodeIDs to set.
     * @return This builder for chaining.
     */
    public Builder setNodeIDs(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureNodeIDsIsMutable();
      nodeIDs_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes nodeIDs = 5;</code>
     * @param value The nodeIDs to add.
     * @return This builder for chaining.
     */
    public Builder addNodeIDs(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureNodeIDsIsMutable();
      nodeIDs_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes nodeIDs = 5;</code>
     * @param values The nodeIDs to add.
     * @return This builder for chaining.
     */
    public Builder addAllNodeIDs(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      ensureNodeIDsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, nodeIDs_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes nodeIDs = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearNodeIDs() {
      nodeIDs_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }

    private long requestCookie_ ;
    /**
     * <code>optional uint64 requestCookie = 6;</code>
     * @return Whether the requestCookie field is set.
     */
    @java.lang.Override
    public boolean hasRequestCookie() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional uint64 requestCookie = 6;</code>
     * @return The requestCookie.
     */
    @java.lang.Override
    public long getRequestCookie() {
      return requestCookie_;
    }
    /**
     * <code>optional uint64 requestCookie = 6;</code>
     * @param value The requestCookie to set.
     * @return This builder for chaining.
     */
    public Builder setRequestCookie(long value) {
      bitField0_ |= 0x00000020;
      requestCookie_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 requestCookie = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestCookie() {
      bitField0_ = (bitField0_ & ~0x00000020);
      requestCookie_ = 0L;
      onChanged();
      return this;
    }

    private int queryType_ = 0;
    /**
     * <code>optional .protocol.TMQueryType queryType = 7;</code>
     * @return Whether the queryType field is set.
     */
    @java.lang.Override public boolean hasQueryType() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional .protocol.TMQueryType queryType = 7;</code>
     * @return The queryType.
     */
    @java.lang.Override
    public protocol.TMQueryType getQueryType() {
      @SuppressWarnings("deprecation")
      protocol.TMQueryType result = protocol.TMQueryType.valueOf(queryType_);
      return result == null ? protocol.TMQueryType.qtINDIRECT : result;
    }
    /**
     * <code>optional .protocol.TMQueryType queryType = 7;</code>
     * @param value The queryType to set.
     * @return This builder for chaining.
     */
    public Builder setQueryType(protocol.TMQueryType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000040;
      queryType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .protocol.TMQueryType queryType = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearQueryType() {
      bitField0_ = (bitField0_ & ~0x00000040);
      queryType_ = 0;
      onChanged();
      return this;
    }

    private int queryDepth_ ;
    /**
     * <pre>
     * How deep to go, number of extra levels
     * </pre>
     *
     * <code>optional uint32 queryDepth = 8;</code>
     * @return Whether the queryDepth field is set.
     */
    @java.lang.Override
    public boolean hasQueryDepth() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     * How deep to go, number of extra levels
     * </pre>
     *
     * <code>optional uint32 queryDepth = 8;</code>
     * @return The queryDepth.
     */
    @java.lang.Override
    public int getQueryDepth() {
      return queryDepth_;
    }
    /**
     * <pre>
     * How deep to go, number of extra levels
     * </pre>
     *
     * <code>optional uint32 queryDepth = 8;</code>
     * @param value The queryDepth to set.
     * @return This builder for chaining.
     */
    public Builder setQueryDepth(int value) {
      bitField0_ |= 0x00000080;
      queryDepth_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * How deep to go, number of extra levels
     * </pre>
     *
     * <code>optional uint32 queryDepth = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearQueryDepth() {
      bitField0_ = (bitField0_ & ~0x00000080);
      queryDepth_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protocol.TMGetLedger)
  }

  // @@protoc_insertion_point(class_scope:protocol.TMGetLedger)
  private static final protocol.TMGetLedger DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protocol.TMGetLedger();
  }

  public static protocol.TMGetLedger getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<TMGetLedger>
      PARSER = new com.google.protobuf.AbstractParser<TMGetLedger>() {
    @java.lang.Override
    public TMGetLedger parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TMGetLedger(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TMGetLedger> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TMGetLedger> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protocol.TMGetLedger getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

