// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ripple.proto

package protocol;

public interface TMGetLedgerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.TMGetLedger)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .protocol.TMLedgerInfoType itype = 1;</code>
   * @return Whether the itype field is set.
   */
  boolean hasItype();
  /**
   * <code>required .protocol.TMLedgerInfoType itype = 1;</code>
   * @return The itype.
   */
  protocol.TMLedgerInfoType getItype();

  /**
   * <code>optional .protocol.TMLedgerType ltype = 2;</code>
   * @return Whether the ltype field is set.
   */
  boolean hasLtype();
  /**
   * <code>optional .protocol.TMLedgerType ltype = 2;</code>
   * @return The ltype.
   */
  protocol.TMLedgerType getLtype();

  /**
   * <pre>
   * Can also be the transaction set hash if liTS_CANDIDATE
   * </pre>
   *
   * <code>optional bytes ledgerHash = 3;</code>
   * @return Whether the ledgerHash field is set.
   */
  boolean hasLedgerHash();
  /**
   * <pre>
   * Can also be the transaction set hash if liTS_CANDIDATE
   * </pre>
   *
   * <code>optional bytes ledgerHash = 3;</code>
   * @return The ledgerHash.
   */
  com.google.protobuf.ByteString getLedgerHash();

  /**
   * <code>optional uint32 ledgerSeq = 4;</code>
   * @return Whether the ledgerSeq field is set.
   */
  boolean hasLedgerSeq();
  /**
   * <code>optional uint32 ledgerSeq = 4;</code>
   * @return The ledgerSeq.
   */
  int getLedgerSeq();

  /**
   * <code>repeated bytes nodeIDs = 5;</code>
   * @return A list containing the nodeIDs.
   */
  java.util.List<com.google.protobuf.ByteString> getNodeIDsList();
  /**
   * <code>repeated bytes nodeIDs = 5;</code>
   * @return The count of nodeIDs.
   */
  int getNodeIDsCount();
  /**
   * <code>repeated bytes nodeIDs = 5;</code>
   * @param index The index of the element to return.
   * @return The nodeIDs at the given index.
   */
  com.google.protobuf.ByteString getNodeIDs(int index);

  /**
   * <code>optional uint64 requestCookie = 6;</code>
   * @return Whether the requestCookie field is set.
   */
  boolean hasRequestCookie();
  /**
   * <code>optional uint64 requestCookie = 6;</code>
   * @return The requestCookie.
   */
  long getRequestCookie();

  /**
   * <code>optional .protocol.TMQueryType queryType = 7;</code>
   * @return Whether the queryType field is set.
   */
  boolean hasQueryType();
  /**
   * <code>optional .protocol.TMQueryType queryType = 7;</code>
   * @return The queryType.
   */
  protocol.TMQueryType getQueryType();

  /**
   * <pre>
   * How deep to go, number of extra levels
   * </pre>
   *
   * <code>optional uint32 queryDepth = 8;</code>
   * @return Whether the queryDepth field is set.
   */
  boolean hasQueryDepth();
  /**
   * <pre>
   * How deep to go, number of extra levels
   * </pre>
   *
   * <code>optional uint32 queryDepth = 8;</code>
   * @return The queryDepth.
   */
  int getQueryDepth();
}
