// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ripple.proto

package protocol;

public interface TMHaveTransactionSetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.TMHaveTransactionSet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .protocol.TxSetStatus status = 1;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>required .protocol.TxSetStatus status = 1;</code>
   * @return The status.
   */
  protocol.TxSetStatus getStatus();

  /**
   * <code>required bytes hash = 2;</code>
   * @return Whether the hash field is set.
   */
  boolean hasHash();
  /**
   * <code>required bytes hash = 2;</code>
   * @return The hash.
   */
  com.google.protobuf.ByteString getHash();
}
