// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ripple.proto

package protocol;

public interface TMIndexedObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.TMIndexedObject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bytes hash = 1;</code>
   * @return Whether the hash field is set.
   */
  boolean hasHash();
  /**
   * <code>optional bytes hash = 1;</code>
   * @return The hash.
   */
  com.google.protobuf.ByteString getHash();

  /**
   * <code>optional bytes nodeID = 2;</code>
   * @return Whether the nodeID field is set.
   */
  boolean hasNodeID();
  /**
   * <code>optional bytes nodeID = 2;</code>
   * @return The nodeID.
   */
  com.google.protobuf.ByteString getNodeID();

  /**
   * <code>optional bytes index = 3;</code>
   * @return Whether the index field is set.
   */
  boolean hasIndex();
  /**
   * <code>optional bytes index = 3;</code>
   * @return The index.
   */
  com.google.protobuf.ByteString getIndex();

  /**
   * <code>optional bytes data = 4;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>optional bytes data = 4;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>optional uint32 ledgerSeq = 5;</code>
   * @return Whether the ledgerSeq field is set.
   */
  boolean hasLedgerSeq();
  /**
   * <code>optional uint32 ledgerSeq = 5;</code>
   * @return The ledgerSeq.
   */
  int getLedgerSeq();
}
