// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ripple.proto

package protocol;

/**
 * Protobuf type {@code protocol.TMIndexedObject}
 */
public final class TMIndexedObject extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protocol.TMIndexedObject)
    TMIndexedObjectOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TMIndexedObject.newBuilder() to construct.
  private TMIndexedObject(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TMIndexedObject() {
    hash_ = com.google.protobuf.ByteString.EMPTY;
    nodeID_ = com.google.protobuf.ByteString.EMPTY;
    index_ = com.google.protobuf.ByteString.EMPTY;
    data_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TMIndexedObject();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TMIndexedObject(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            bitField0_ |= 0x00000001;
            hash_ = input.readBytes();
            break;
          }
          case 18: {
            bitField0_ |= 0x00000002;
            nodeID_ = input.readBytes();
            break;
          }
          case 26: {
            bitField0_ |= 0x00000004;
            index_ = input.readBytes();
            break;
          }
          case 34: {
            bitField0_ |= 0x00000008;
            data_ = input.readBytes();
            break;
          }
          case 40: {
            bitField0_ |= 0x00000010;
            ledgerSeq_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protocol.Ripple.internal_static_protocol_TMIndexedObject_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protocol.Ripple.internal_static_protocol_TMIndexedObject_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protocol.TMIndexedObject.class, protocol.TMIndexedObject.Builder.class);
  }

  private int bitField0_;
  public static final int HASH_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString hash_;
  /**
   * <code>optional bytes hash = 1;</code>
   * @return Whether the hash field is set.
   */
  @java.lang.Override
  public boolean hasHash() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional bytes hash = 1;</code>
   * @return The hash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getHash() {
    return hash_;
  }

  public static final int NODEID_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString nodeID_;
  /**
   * <code>optional bytes nodeID = 2;</code>
   * @return Whether the nodeID field is set.
   */
  @java.lang.Override
  public boolean hasNodeID() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional bytes nodeID = 2;</code>
   * @return The nodeID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getNodeID() {
    return nodeID_;
  }

  public static final int INDEX_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString index_;
  /**
   * <code>optional bytes index = 3;</code>
   * @return Whether the index field is set.
   */
  @java.lang.Override
  public boolean hasIndex() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional bytes index = 3;</code>
   * @return The index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getIndex() {
    return index_;
  }

  public static final int DATA_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString data_;
  /**
   * <code>optional bytes data = 4;</code>
   * @return Whether the data field is set.
   */
  @java.lang.Override
  public boolean hasData() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional bytes data = 4;</code>
   * @return The data.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getData() {
    return data_;
  }

  public static final int LEDGERSEQ_FIELD_NUMBER = 5;
  private int ledgerSeq_;
  /**
   * <code>optional uint32 ledgerSeq = 5;</code>
   * @return Whether the ledgerSeq field is set.
   */
  @java.lang.Override
  public boolean hasLedgerSeq() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional uint32 ledgerSeq = 5;</code>
   * @return The ledgerSeq.
   */
  @java.lang.Override
  public int getLedgerSeq() {
    return ledgerSeq_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBytes(1, hash_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeBytes(2, nodeID_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeBytes(3, index_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeBytes(4, data_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeUInt32(5, ledgerSeq_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, hash_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, nodeID_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, index_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, data_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, ledgerSeq_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protocol.TMIndexedObject)) {
      return super.equals(obj);
    }
    protocol.TMIndexedObject other = (protocol.TMIndexedObject) obj;

    if (hasHash() != other.hasHash()) return false;
    if (hasHash()) {
      if (!getHash()
          .equals(other.getHash())) return false;
    }
    if (hasNodeID() != other.hasNodeID()) return false;
    if (hasNodeID()) {
      if (!getNodeID()
          .equals(other.getNodeID())) return false;
    }
    if (hasIndex() != other.hasIndex()) return false;
    if (hasIndex()) {
      if (!getIndex()
          .equals(other.getIndex())) return false;
    }
    if (hasData() != other.hasData()) return false;
    if (hasData()) {
      if (!getData()
          .equals(other.getData())) return false;
    }
    if (hasLedgerSeq() != other.hasLedgerSeq()) return false;
    if (hasLedgerSeq()) {
      if (getLedgerSeq()
          != other.getLedgerSeq()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHash()) {
      hash = (37 * hash) + HASH_FIELD_NUMBER;
      hash = (53 * hash) + getHash().hashCode();
    }
    if (hasNodeID()) {
      hash = (37 * hash) + NODEID_FIELD_NUMBER;
      hash = (53 * hash) + getNodeID().hashCode();
    }
    if (hasIndex()) {
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getIndex().hashCode();
    }
    if (hasData()) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
    }
    if (hasLedgerSeq()) {
      hash = (37 * hash) + LEDGERSEQ_FIELD_NUMBER;
      hash = (53 * hash) + getLedgerSeq();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protocol.TMIndexedObject parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol.TMIndexedObject parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol.TMIndexedObject parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol.TMIndexedObject parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol.TMIndexedObject parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol.TMIndexedObject parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol.TMIndexedObject parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protocol.TMIndexedObject parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protocol.TMIndexedObject parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protocol.TMIndexedObject parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protocol.TMIndexedObject parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protocol.TMIndexedObject parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protocol.TMIndexedObject prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protocol.TMIndexedObject}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol.TMIndexedObject)
      protocol.TMIndexedObjectOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Ripple.internal_static_protocol_TMIndexedObject_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Ripple.internal_static_protocol_TMIndexedObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.TMIndexedObject.class, protocol.TMIndexedObject.Builder.class);
    }

    // Construct using protocol.TMIndexedObject.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      hash_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      nodeID_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      index_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      data_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      ledgerSeq_ = 0;
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protocol.Ripple.internal_static_protocol_TMIndexedObject_descriptor;
    }

    @java.lang.Override
    public protocol.TMIndexedObject getDefaultInstanceForType() {
      return protocol.TMIndexedObject.getDefaultInstance();
    }

    @java.lang.Override
    public protocol.TMIndexedObject build() {
      protocol.TMIndexedObject result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protocol.TMIndexedObject buildPartial() {
      protocol.TMIndexedObject result = new protocol.TMIndexedObject(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.hash_ = hash_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.nodeID_ = nodeID_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.index_ = index_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.data_ = data_;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.ledgerSeq_ = ledgerSeq_;
        to_bitField0_ |= 0x00000010;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protocol.TMIndexedObject) {
        return mergeFrom((protocol.TMIndexedObject)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protocol.TMIndexedObject other) {
      if (other == protocol.TMIndexedObject.getDefaultInstance()) return this;
      if (other.hasHash()) {
        setHash(other.getHash());
      }
      if (other.hasNodeID()) {
        setNodeID(other.getNodeID());
      }
      if (other.hasIndex()) {
        setIndex(other.getIndex());
      }
      if (other.hasData()) {
        setData(other.getData());
      }
      if (other.hasLedgerSeq()) {
        setLedgerSeq(other.getLedgerSeq());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protocol.TMIndexedObject parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protocol.TMIndexedObject) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString hash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes hash = 1;</code>
     * @return Whether the hash field is set.
     */
    @java.lang.Override
    public boolean hasHash() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bytes hash = 1;</code>
     * @return The hash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getHash() {
      return hash_;
    }
    /**
     * <code>optional bytes hash = 1;</code>
     * @param value The hash to set.
     * @return This builder for chaining.
     */
    public Builder setHash(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      hash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes hash = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearHash() {
      bitField0_ = (bitField0_ & ~0x00000001);
      hash_ = getDefaultInstance().getHash();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString nodeID_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes nodeID = 2;</code>
     * @return Whether the nodeID field is set.
     */
    @java.lang.Override
    public boolean hasNodeID() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bytes nodeID = 2;</code>
     * @return The nodeID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getNodeID() {
      return nodeID_;
    }
    /**
     * <code>optional bytes nodeID = 2;</code>
     * @param value The nodeID to set.
     * @return This builder for chaining.
     */
    public Builder setNodeID(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      nodeID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes nodeID = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNodeID() {
      bitField0_ = (bitField0_ & ~0x00000002);
      nodeID_ = getDefaultInstance().getNodeID();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString index_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes index = 3;</code>
     * @return Whether the index field is set.
     */
    @java.lang.Override
    public boolean hasIndex() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional bytes index = 3;</code>
     * @return The index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getIndex() {
      return index_;
    }
    /**
     * <code>optional bytes index = 3;</code>
     * @param value The index to set.
     * @return This builder for chaining.
     */
    public Builder setIndex(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      index_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes index = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIndex() {
      bitField0_ = (bitField0_ & ~0x00000004);
      index_ = getDefaultInstance().getIndex();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes data = 4;</code>
     * @return Whether the data field is set.
     */
    @java.lang.Override
    public boolean hasData() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bytes data = 4;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <code>optional bytes data = 4;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      data_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes data = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      bitField0_ = (bitField0_ & ~0x00000008);
      data_ = getDefaultInstance().getData();
      onChanged();
      return this;
    }

    private int ledgerSeq_ ;
    /**
     * <code>optional uint32 ledgerSeq = 5;</code>
     * @return Whether the ledgerSeq field is set.
     */
    @java.lang.Override
    public boolean hasLedgerSeq() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional uint32 ledgerSeq = 5;</code>
     * @return The ledgerSeq.
     */
    @java.lang.Override
    public int getLedgerSeq() {
      return ledgerSeq_;
    }
    /**
     * <code>optional uint32 ledgerSeq = 5;</code>
     * @param value The ledgerSeq to set.
     * @return This builder for chaining.
     */
    public Builder setLedgerSeq(int value) {
      bitField0_ |= 0x00000010;
      ledgerSeq_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 ledgerSeq = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearLedgerSeq() {
      bitField0_ = (bitField0_ & ~0x00000010);
      ledgerSeq_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protocol.TMIndexedObject)
  }

  // @@protoc_insertion_point(class_scope:protocol.TMIndexedObject)
  private static final protocol.TMIndexedObject DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protocol.TMIndexedObject();
  }

  public static protocol.TMIndexedObject getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<TMIndexedObject>
      PARSER = new com.google.protobuf.AbstractParser<TMIndexedObject>() {
    @java.lang.Override
    public TMIndexedObject parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TMIndexedObject(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TMIndexedObject> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TMIndexedObject> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protocol.TMIndexedObject getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

