// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ripple.proto

package protocol;

/**
 * Protobuf enum {@code protocol.TMLedgerMapType}
 */
public enum TMLedgerMapType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * transaction map
   * </pre>
   *
   * <code>lmTRANASCTION = 1;</code>
   */
  lmTRANASCTION(1),
  /**
   * <pre>
   * account state map
   * </pre>
   *
   * <code>lmACCOUNT_STATE = 2;</code>
   */
  lmACCOUNT_STATE(2),
  ;

  /**
   * <pre>
   * transaction map
   * </pre>
   *
   * <code>lmTRANASCTION = 1;</code>
   */
  public static final int lmTRANASCTION_VALUE = 1;
  /**
   * <pre>
   * account state map
   * </pre>
   *
   * <code>lmACCOUNT_STATE = 2;</code>
   */
  public static final int lmACCOUNT_STATE_VALUE = 2;


  public final int getNumber() {
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TMLedgerMapType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static TMLedgerMapType forNumber(int value) {
    switch (value) {
      case 1: return lmTRANASCTION;
      case 2: return lmACCOUNT_STATE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TMLedgerMapType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TMLedgerMapType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TMLedgerMapType>() {
          public TMLedgerMapType findValueByNumber(int number) {
            return TMLedgerMapType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return protocol.Ripple.getDescriptor().getEnumTypes().get(9);
  }

  private static final TMLedgerMapType[] VALUES = values();

  public static TMLedgerMapType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TMLedgerMapType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:protocol.TMLedgerMapType)
}

