// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ripple.proto

package protocol;

public interface TMLinkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.TMLink)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * node public key
   * </pre>
   *
   * <code>required bytes nodePubKey = 1;</code>
   * @return Whether the nodePubKey field is set.
   */
  boolean hasNodePubKey();
  /**
   * <pre>
   * node public key
   * </pre>
   *
   * <code>required bytes nodePubKey = 1;</code>
   * @return The nodePubKey.
   */
  com.google.protobuf.ByteString getNodePubKey();
}
