// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ripple.proto

package protocol;

public interface TMLoadSourceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.TMLoadSource)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string name = 1;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>required string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>required string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>required uint32 cost = 2;</code>
   * @return Whether the cost field is set.
   */
  boolean hasCost();
  /**
   * <code>required uint32 cost = 2;</code>
   * @return The cost.
   */
  int getCost();

  /**
   * <pre>
   * number of connections
   * </pre>
   *
   * <code>optional uint32 count = 3;</code>
   * @return Whether the count field is set.
   */
  boolean hasCount();
  /**
   * <pre>
   * number of connections
   * </pre>
   *
   * <code>optional uint32 count = 3;</code>
   * @return The count.
   */
  int getCount();
}
