// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ripple.proto

package protocol;

public interface TMManifestsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.TMManifests)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .protocol.TMManifest list = 1;</code>
   */
  java.util.List<protocol.TMManifest> 
      getListList();
  /**
   * <code>repeated .protocol.TMManifest list = 1;</code>
   */
  protocol.TMManifest getList(int index);
  /**
   * <code>repeated .protocol.TMManifest list = 1;</code>
   */
  int getListCount();
  /**
   * <code>repeated .protocol.TMManifest list = 1;</code>
   */
  java.util.List<? extends protocol.TMManifestOrBuilder> 
      getListOrBuilderList();
  /**
   * <code>repeated .protocol.TMManifest list = 1;</code>
   */
  protocol.TMManifestOrBuilder getListOrBuilder(
      int index);

  /**
   * <pre>
   * The manifests sent when a peer first connects to another peer are `history`.
   * </pre>
   *
   * <code>optional bool history = 2 [deprecated = true];</code>
   * @return Whether the history field is set.
   */
  @java.lang.Deprecated boolean hasHistory();
  /**
   * <pre>
   * The manifests sent when a peer first connects to another peer are `history`.
   * </pre>
   *
   * <code>optional bool history = 2 [deprecated = true];</code>
   * @return The history.
   */
  @java.lang.Deprecated boolean getHistory();
}
