// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ripple.proto

package protocol;

/**
 * <pre>
 * Info about shards held
 * </pre>
 *
 * Protobuf type {@code protocol.TMPeerShardInfo}
 */
public final class TMPeerShardInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protocol.TMPeerShardInfo)
    TMPeerShardInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TMPeerShardInfo.newBuilder() to construct.
  private TMPeerShardInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TMPeerShardInfo() {
    shardIndexes_ = "";
    nodePubKey_ = com.google.protobuf.ByteString.EMPTY;
    endpoint_ = "";
    peerChain_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TMPeerShardInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TMPeerShardInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            shardIndexes_ = bs;
            break;
          }
          case 18: {
            bitField0_ |= 0x00000002;
            nodePubKey_ = input.readBytes();
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            endpoint_ = bs;
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            lastLink_ = input.readBool();
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) != 0)) {
              peerChain_ = new java.util.ArrayList<protocol.TMLink>();
              mutable_bitField0_ |= 0x00000010;
            }
            peerChain_.add(
                input.readMessage(protocol.TMLink.PARSER, extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) != 0)) {
        peerChain_ = java.util.Collections.unmodifiableList(peerChain_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protocol.Ripple.internal_static_protocol_TMPeerShardInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protocol.Ripple.internal_static_protocol_TMPeerShardInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protocol.TMPeerShardInfo.class, protocol.TMPeerShardInfo.Builder.class);
  }

  private int bitField0_;
  public static final int SHARDINDEXES_FIELD_NUMBER = 1;
  private volatile java.lang.Object shardIndexes_;
  /**
   * <pre>
   * rangeSet of shard indexes
   * </pre>
   *
   * <code>required string shardIndexes = 1;</code>
   * @return Whether the shardIndexes field is set.
   */
  @java.lang.Override
  public boolean hasShardIndexes() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * rangeSet of shard indexes
   * </pre>
   *
   * <code>required string shardIndexes = 1;</code>
   * @return The shardIndexes.
   */
  @java.lang.Override
  public java.lang.String getShardIndexes() {
    java.lang.Object ref = shardIndexes_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        shardIndexes_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * rangeSet of shard indexes
   * </pre>
   *
   * <code>required string shardIndexes = 1;</code>
   * @return The bytes for shardIndexes.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getShardIndexesBytes() {
    java.lang.Object ref = shardIndexes_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      shardIndexes_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NODEPUBKEY_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString nodePubKey_;
  /**
   * <pre>
   * node public key
   * </pre>
   *
   * <code>optional bytes nodePubKey = 2;</code>
   * @return Whether the nodePubKey field is set.
   */
  @java.lang.Override
  public boolean hasNodePubKey() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * node public key
   * </pre>
   *
   * <code>optional bytes nodePubKey = 2;</code>
   * @return The nodePubKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getNodePubKey() {
    return nodePubKey_;
  }

  public static final int ENDPOINT_FIELD_NUMBER = 3;
  private volatile java.lang.Object endpoint_;
  /**
   * <pre>
   * ipv6 or ipv4 address
   * </pre>
   *
   * <code>optional string endpoint = 3;</code>
   * @return Whether the endpoint field is set.
   */
  @java.lang.Override
  public boolean hasEndpoint() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * ipv6 or ipv4 address
   * </pre>
   *
   * <code>optional string endpoint = 3;</code>
   * @return The endpoint.
   */
  @java.lang.Override
  public java.lang.String getEndpoint() {
    java.lang.Object ref = endpoint_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        endpoint_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * ipv6 or ipv4 address
   * </pre>
   *
   * <code>optional string endpoint = 3;</code>
   * @return The bytes for endpoint.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEndpointBytes() {
    java.lang.Object ref = endpoint_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      endpoint_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LASTLINK_FIELD_NUMBER = 4;
  private boolean lastLink_;
  /**
   * <pre>
   * true if last link in the peer chain
   * </pre>
   *
   * <code>optional bool lastLink = 4;</code>
   * @return Whether the lastLink field is set.
   */
  @java.lang.Override
  public boolean hasLastLink() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * true if last link in the peer chain
   * </pre>
   *
   * <code>optional bool lastLink = 4;</code>
   * @return The lastLink.
   */
  @java.lang.Override
  public boolean getLastLink() {
    return lastLink_;
  }

  public static final int PEERCHAIN_FIELD_NUMBER = 5;
  private java.util.List<protocol.TMLink> peerChain_;
  /**
   * <pre>
   * public keys used to route messages
   * </pre>
   *
   * <code>repeated .protocol.TMLink peerChain = 5;</code>
   */
  @java.lang.Override
  public java.util.List<protocol.TMLink> getPeerChainList() {
    return peerChain_;
  }
  /**
   * <pre>
   * public keys used to route messages
   * </pre>
   *
   * <code>repeated .protocol.TMLink peerChain = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends protocol.TMLinkOrBuilder> 
      getPeerChainOrBuilderList() {
    return peerChain_;
  }
  /**
   * <pre>
   * public keys used to route messages
   * </pre>
   *
   * <code>repeated .protocol.TMLink peerChain = 5;</code>
   */
  @java.lang.Override
  public int getPeerChainCount() {
    return peerChain_.size();
  }
  /**
   * <pre>
   * public keys used to route messages
   * </pre>
   *
   * <code>repeated .protocol.TMLink peerChain = 5;</code>
   */
  @java.lang.Override
  public protocol.TMLink getPeerChain(int index) {
    return peerChain_.get(index);
  }
  /**
   * <pre>
   * public keys used to route messages
   * </pre>
   *
   * <code>repeated .protocol.TMLink peerChain = 5;</code>
   */
  @java.lang.Override
  public protocol.TMLinkOrBuilder getPeerChainOrBuilder(
      int index) {
    return peerChain_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasShardIndexes()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getPeerChainCount(); i++) {
      if (!getPeerChain(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, shardIndexes_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeBytes(2, nodePubKey_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, endpoint_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeBool(4, lastLink_);
    }
    for (int i = 0; i < peerChain_.size(); i++) {
      output.writeMessage(5, peerChain_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, shardIndexes_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, nodePubKey_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, endpoint_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, lastLink_);
    }
    for (int i = 0; i < peerChain_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, peerChain_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protocol.TMPeerShardInfo)) {
      return super.equals(obj);
    }
    protocol.TMPeerShardInfo other = (protocol.TMPeerShardInfo) obj;

    if (hasShardIndexes() != other.hasShardIndexes()) return false;
    if (hasShardIndexes()) {
      if (!getShardIndexes()
          .equals(other.getShardIndexes())) return false;
    }
    if (hasNodePubKey() != other.hasNodePubKey()) return false;
    if (hasNodePubKey()) {
      if (!getNodePubKey()
          .equals(other.getNodePubKey())) return false;
    }
    if (hasEndpoint() != other.hasEndpoint()) return false;
    if (hasEndpoint()) {
      if (!getEndpoint()
          .equals(other.getEndpoint())) return false;
    }
    if (hasLastLink() != other.hasLastLink()) return false;
    if (hasLastLink()) {
      if (getLastLink()
          != other.getLastLink()) return false;
    }
    if (!getPeerChainList()
        .equals(other.getPeerChainList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasShardIndexes()) {
      hash = (37 * hash) + SHARDINDEXES_FIELD_NUMBER;
      hash = (53 * hash) + getShardIndexes().hashCode();
    }
    if (hasNodePubKey()) {
      hash = (37 * hash) + NODEPUBKEY_FIELD_NUMBER;
      hash = (53 * hash) + getNodePubKey().hashCode();
    }
    if (hasEndpoint()) {
      hash = (37 * hash) + ENDPOINT_FIELD_NUMBER;
      hash = (53 * hash) + getEndpoint().hashCode();
    }
    if (hasLastLink()) {
      hash = (37 * hash) + LASTLINK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getLastLink());
    }
    if (getPeerChainCount() > 0) {
      hash = (37 * hash) + PEERCHAIN_FIELD_NUMBER;
      hash = (53 * hash) + getPeerChainList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protocol.TMPeerShardInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol.TMPeerShardInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol.TMPeerShardInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol.TMPeerShardInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol.TMPeerShardInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol.TMPeerShardInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol.TMPeerShardInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protocol.TMPeerShardInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protocol.TMPeerShardInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protocol.TMPeerShardInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protocol.TMPeerShardInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protocol.TMPeerShardInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protocol.TMPeerShardInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Info about shards held
   * </pre>
   *
   * Protobuf type {@code protocol.TMPeerShardInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol.TMPeerShardInfo)
      protocol.TMPeerShardInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Ripple.internal_static_protocol_TMPeerShardInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Ripple.internal_static_protocol_TMPeerShardInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.TMPeerShardInfo.class, protocol.TMPeerShardInfo.Builder.class);
    }

    // Construct using protocol.TMPeerShardInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPeerChainFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      shardIndexes_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      nodePubKey_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      endpoint_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      lastLink_ = false;
      bitField0_ = (bitField0_ & ~0x00000008);
      if (peerChainBuilder_ == null) {
        peerChain_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        peerChainBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protocol.Ripple.internal_static_protocol_TMPeerShardInfo_descriptor;
    }

    @java.lang.Override
    public protocol.TMPeerShardInfo getDefaultInstanceForType() {
      return protocol.TMPeerShardInfo.getDefaultInstance();
    }

    @java.lang.Override
    public protocol.TMPeerShardInfo build() {
      protocol.TMPeerShardInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protocol.TMPeerShardInfo buildPartial() {
      protocol.TMPeerShardInfo result = new protocol.TMPeerShardInfo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.shardIndexes_ = shardIndexes_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.nodePubKey_ = nodePubKey_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.endpoint_ = endpoint_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.lastLink_ = lastLink_;
        to_bitField0_ |= 0x00000008;
      }
      if (peerChainBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          peerChain_ = java.util.Collections.unmodifiableList(peerChain_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.peerChain_ = peerChain_;
      } else {
        result.peerChain_ = peerChainBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protocol.TMPeerShardInfo) {
        return mergeFrom((protocol.TMPeerShardInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protocol.TMPeerShardInfo other) {
      if (other == protocol.TMPeerShardInfo.getDefaultInstance()) return this;
      if (other.hasShardIndexes()) {
        bitField0_ |= 0x00000001;
        shardIndexes_ = other.shardIndexes_;
        onChanged();
      }
      if (other.hasNodePubKey()) {
        setNodePubKey(other.getNodePubKey());
      }
      if (other.hasEndpoint()) {
        bitField0_ |= 0x00000004;
        endpoint_ = other.endpoint_;
        onChanged();
      }
      if (other.hasLastLink()) {
        setLastLink(other.getLastLink());
      }
      if (peerChainBuilder_ == null) {
        if (!other.peerChain_.isEmpty()) {
          if (peerChain_.isEmpty()) {
            peerChain_ = other.peerChain_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensurePeerChainIsMutable();
            peerChain_.addAll(other.peerChain_);
          }
          onChanged();
        }
      } else {
        if (!other.peerChain_.isEmpty()) {
          if (peerChainBuilder_.isEmpty()) {
            peerChainBuilder_.dispose();
            peerChainBuilder_ = null;
            peerChain_ = other.peerChain_;
            bitField0_ = (bitField0_ & ~0x00000010);
            peerChainBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPeerChainFieldBuilder() : null;
          } else {
            peerChainBuilder_.addAllMessages(other.peerChain_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasShardIndexes()) {
        return false;
      }
      for (int i = 0; i < getPeerChainCount(); i++) {
        if (!getPeerChain(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protocol.TMPeerShardInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protocol.TMPeerShardInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object shardIndexes_ = "";
    /**
     * <pre>
     * rangeSet of shard indexes
     * </pre>
     *
     * <code>required string shardIndexes = 1;</code>
     * @return Whether the shardIndexes field is set.
     */
    public boolean hasShardIndexes() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * rangeSet of shard indexes
     * </pre>
     *
     * <code>required string shardIndexes = 1;</code>
     * @return The shardIndexes.
     */
    public java.lang.String getShardIndexes() {
      java.lang.Object ref = shardIndexes_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          shardIndexes_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * rangeSet of shard indexes
     * </pre>
     *
     * <code>required string shardIndexes = 1;</code>
     * @return The bytes for shardIndexes.
     */
    public com.google.protobuf.ByteString
        getShardIndexesBytes() {
      java.lang.Object ref = shardIndexes_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shardIndexes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * rangeSet of shard indexes
     * </pre>
     *
     * <code>required string shardIndexes = 1;</code>
     * @param value The shardIndexes to set.
     * @return This builder for chaining.
     */
    public Builder setShardIndexes(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      shardIndexes_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * rangeSet of shard indexes
     * </pre>
     *
     * <code>required string shardIndexes = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearShardIndexes() {
      bitField0_ = (bitField0_ & ~0x00000001);
      shardIndexes_ = getDefaultInstance().getShardIndexes();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * rangeSet of shard indexes
     * </pre>
     *
     * <code>required string shardIndexes = 1;</code>
     * @param value The bytes for shardIndexes to set.
     * @return This builder for chaining.
     */
    public Builder setShardIndexesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      shardIndexes_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString nodePubKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * node public key
     * </pre>
     *
     * <code>optional bytes nodePubKey = 2;</code>
     * @return Whether the nodePubKey field is set.
     */
    @java.lang.Override
    public boolean hasNodePubKey() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * node public key
     * </pre>
     *
     * <code>optional bytes nodePubKey = 2;</code>
     * @return The nodePubKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getNodePubKey() {
      return nodePubKey_;
    }
    /**
     * <pre>
     * node public key
     * </pre>
     *
     * <code>optional bytes nodePubKey = 2;</code>
     * @param value The nodePubKey to set.
     * @return This builder for chaining.
     */
    public Builder setNodePubKey(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      nodePubKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * node public key
     * </pre>
     *
     * <code>optional bytes nodePubKey = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNodePubKey() {
      bitField0_ = (bitField0_ & ~0x00000002);
      nodePubKey_ = getDefaultInstance().getNodePubKey();
      onChanged();
      return this;
    }

    private java.lang.Object endpoint_ = "";
    /**
     * <pre>
     * ipv6 or ipv4 address
     * </pre>
     *
     * <code>optional string endpoint = 3;</code>
     * @return Whether the endpoint field is set.
     */
    public boolean hasEndpoint() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * ipv6 or ipv4 address
     * </pre>
     *
     * <code>optional string endpoint = 3;</code>
     * @return The endpoint.
     */
    public java.lang.String getEndpoint() {
      java.lang.Object ref = endpoint_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          endpoint_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ipv6 or ipv4 address
     * </pre>
     *
     * <code>optional string endpoint = 3;</code>
     * @return The bytes for endpoint.
     */
    public com.google.protobuf.ByteString
        getEndpointBytes() {
      java.lang.Object ref = endpoint_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endpoint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ipv6 or ipv4 address
     * </pre>
     *
     * <code>optional string endpoint = 3;</code>
     * @param value The endpoint to set.
     * @return This builder for chaining.
     */
    public Builder setEndpoint(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      endpoint_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ipv6 or ipv4 address
     * </pre>
     *
     * <code>optional string endpoint = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndpoint() {
      bitField0_ = (bitField0_ & ~0x00000004);
      endpoint_ = getDefaultInstance().getEndpoint();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ipv6 or ipv4 address
     * </pre>
     *
     * <code>optional string endpoint = 3;</code>
     * @param value The bytes for endpoint to set.
     * @return This builder for chaining.
     */
    public Builder setEndpointBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      endpoint_ = value;
      onChanged();
      return this;
    }

    private boolean lastLink_ ;
    /**
     * <pre>
     * true if last link in the peer chain
     * </pre>
     *
     * <code>optional bool lastLink = 4;</code>
     * @return Whether the lastLink field is set.
     */
    @java.lang.Override
    public boolean hasLastLink() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * true if last link in the peer chain
     * </pre>
     *
     * <code>optional bool lastLink = 4;</code>
     * @return The lastLink.
     */
    @java.lang.Override
    public boolean getLastLink() {
      return lastLink_;
    }
    /**
     * <pre>
     * true if last link in the peer chain
     * </pre>
     *
     * <code>optional bool lastLink = 4;</code>
     * @param value The lastLink to set.
     * @return This builder for chaining.
     */
    public Builder setLastLink(boolean value) {
      bitField0_ |= 0x00000008;
      lastLink_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * true if last link in the peer chain
     * </pre>
     *
     * <code>optional bool lastLink = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastLink() {
      bitField0_ = (bitField0_ & ~0x00000008);
      lastLink_ = false;
      onChanged();
      return this;
    }

    private java.util.List<protocol.TMLink> peerChain_ =
      java.util.Collections.emptyList();
    private void ensurePeerChainIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        peerChain_ = new java.util.ArrayList<protocol.TMLink>(peerChain_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        protocol.TMLink, protocol.TMLink.Builder, protocol.TMLinkOrBuilder> peerChainBuilder_;

    /**
     * <pre>
     * public keys used to route messages
     * </pre>
     *
     * <code>repeated .protocol.TMLink peerChain = 5;</code>
     */
    public java.util.List<protocol.TMLink> getPeerChainList() {
      if (peerChainBuilder_ == null) {
        return java.util.Collections.unmodifiableList(peerChain_);
      } else {
        return peerChainBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * public keys used to route messages
     * </pre>
     *
     * <code>repeated .protocol.TMLink peerChain = 5;</code>
     */
    public int getPeerChainCount() {
      if (peerChainBuilder_ == null) {
        return peerChain_.size();
      } else {
        return peerChainBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * public keys used to route messages
     * </pre>
     *
     * <code>repeated .protocol.TMLink peerChain = 5;</code>
     */
    public protocol.TMLink getPeerChain(int index) {
      if (peerChainBuilder_ == null) {
        return peerChain_.get(index);
      } else {
        return peerChainBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * public keys used to route messages
     * </pre>
     *
     * <code>repeated .protocol.TMLink peerChain = 5;</code>
     */
    public Builder setPeerChain(
        int index, protocol.TMLink value) {
      if (peerChainBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePeerChainIsMutable();
        peerChain_.set(index, value);
        onChanged();
      } else {
        peerChainBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * public keys used to route messages
     * </pre>
     *
     * <code>repeated .protocol.TMLink peerChain = 5;</code>
     */
    public Builder setPeerChain(
        int index, protocol.TMLink.Builder builderForValue) {
      if (peerChainBuilder_ == null) {
        ensurePeerChainIsMutable();
        peerChain_.set(index, builderForValue.build());
        onChanged();
      } else {
        peerChainBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * public keys used to route messages
     * </pre>
     *
     * <code>repeated .protocol.TMLink peerChain = 5;</code>
     */
    public Builder addPeerChain(protocol.TMLink value) {
      if (peerChainBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePeerChainIsMutable();
        peerChain_.add(value);
        onChanged();
      } else {
        peerChainBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * public keys used to route messages
     * </pre>
     *
     * <code>repeated .protocol.TMLink peerChain = 5;</code>
     */
    public Builder addPeerChain(
        int index, protocol.TMLink value) {
      if (peerChainBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePeerChainIsMutable();
        peerChain_.add(index, value);
        onChanged();
      } else {
        peerChainBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * public keys used to route messages
     * </pre>
     *
     * <code>repeated .protocol.TMLink peerChain = 5;</code>
     */
    public Builder addPeerChain(
        protocol.TMLink.Builder builderForValue) {
      if (peerChainBuilder_ == null) {
        ensurePeerChainIsMutable();
        peerChain_.add(builderForValue.build());
        onChanged();
      } else {
        peerChainBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * public keys used to route messages
     * </pre>
     *
     * <code>repeated .protocol.TMLink peerChain = 5;</code>
     */
    public Builder addPeerChain(
        int index, protocol.TMLink.Builder builderForValue) {
      if (peerChainBuilder_ == null) {
        ensurePeerChainIsMutable();
        peerChain_.add(index, builderForValue.build());
        onChanged();
      } else {
        peerChainBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * public keys used to route messages
     * </pre>
     *
     * <code>repeated .protocol.TMLink peerChain = 5;</code>
     */
    public Builder addAllPeerChain(
        java.lang.Iterable<? extends protocol.TMLink> values) {
      if (peerChainBuilder_ == null) {
        ensurePeerChainIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, peerChain_);
        onChanged();
      } else {
        peerChainBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * public keys used to route messages
     * </pre>
     *
     * <code>repeated .protocol.TMLink peerChain = 5;</code>
     */
    public Builder clearPeerChain() {
      if (peerChainBuilder_ == null) {
        peerChain_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        peerChainBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * public keys used to route messages
     * </pre>
     *
     * <code>repeated .protocol.TMLink peerChain = 5;</code>
     */
    public Builder removePeerChain(int index) {
      if (peerChainBuilder_ == null) {
        ensurePeerChainIsMutable();
        peerChain_.remove(index);
        onChanged();
      } else {
        peerChainBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * public keys used to route messages
     * </pre>
     *
     * <code>repeated .protocol.TMLink peerChain = 5;</code>
     */
    public protocol.TMLink.Builder getPeerChainBuilder(
        int index) {
      return getPeerChainFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * public keys used to route messages
     * </pre>
     *
     * <code>repeated .protocol.TMLink peerChain = 5;</code>
     */
    public protocol.TMLinkOrBuilder getPeerChainOrBuilder(
        int index) {
      if (peerChainBuilder_ == null) {
        return peerChain_.get(index);  } else {
        return peerChainBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * public keys used to route messages
     * </pre>
     *
     * <code>repeated .protocol.TMLink peerChain = 5;</code>
     */
    public java.util.List<? extends protocol.TMLinkOrBuilder> 
         getPeerChainOrBuilderList() {
      if (peerChainBuilder_ != null) {
        return peerChainBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(peerChain_);
      }
    }
    /**
     * <pre>
     * public keys used to route messages
     * </pre>
     *
     * <code>repeated .protocol.TMLink peerChain = 5;</code>
     */
    public protocol.TMLink.Builder addPeerChainBuilder() {
      return getPeerChainFieldBuilder().addBuilder(
          protocol.TMLink.getDefaultInstance());
    }
    /**
     * <pre>
     * public keys used to route messages
     * </pre>
     *
     * <code>repeated .protocol.TMLink peerChain = 5;</code>
     */
    public protocol.TMLink.Builder addPeerChainBuilder(
        int index) {
      return getPeerChainFieldBuilder().addBuilder(
          index, protocol.TMLink.getDefaultInstance());
    }
    /**
     * <pre>
     * public keys used to route messages
     * </pre>
     *
     * <code>repeated .protocol.TMLink peerChain = 5;</code>
     */
    public java.util.List<protocol.TMLink.Builder> 
         getPeerChainBuilderList() {
      return getPeerChainFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        protocol.TMLink, protocol.TMLink.Builder, protocol.TMLinkOrBuilder> 
        getPeerChainFieldBuilder() {
      if (peerChainBuilder_ == null) {
        peerChainBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            protocol.TMLink, protocol.TMLink.Builder, protocol.TMLinkOrBuilder>(
                peerChain_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        peerChain_ = null;
      }
      return peerChainBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protocol.TMPeerShardInfo)
  }

  // @@protoc_insertion_point(class_scope:protocol.TMPeerShardInfo)
  private static final protocol.TMPeerShardInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protocol.TMPeerShardInfo();
  }

  public static protocol.TMPeerShardInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<TMPeerShardInfo>
      PARSER = new com.google.protobuf.AbstractParser<TMPeerShardInfo>() {
    @java.lang.Override
    public TMPeerShardInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TMPeerShardInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TMPeerShardInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TMPeerShardInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protocol.TMPeerShardInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

