// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ripple.proto

package protocol;

/**
 * Protobuf type {@code protocol.TMSquelch}
 */
public final class TMSquelch extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protocol.TMSquelch)
    TMSquelchOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TMSquelch.newBuilder() to construct.
  private TMSquelch(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TMSquelch() {
    validatorPubKey_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TMSquelch();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TMSquelch(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            squelch_ = input.readBool();
            break;
          }
          case 18: {
            bitField0_ |= 0x00000002;
            validatorPubKey_ = input.readBytes();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            squelchDuration_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protocol.Ripple.internal_static_protocol_TMSquelch_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protocol.Ripple.internal_static_protocol_TMSquelch_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protocol.TMSquelch.class, protocol.TMSquelch.Builder.class);
  }

  private int bitField0_;
  public static final int SQUELCH_FIELD_NUMBER = 1;
  private boolean squelch_;
  /**
   * <pre>
   * squelch if true, otherwise unsquelch
   * </pre>
   *
   * <code>required bool squelch = 1;</code>
   * @return Whether the squelch field is set.
   */
  @java.lang.Override
  public boolean hasSquelch() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * squelch if true, otherwise unsquelch
   * </pre>
   *
   * <code>required bool squelch = 1;</code>
   * @return The squelch.
   */
  @java.lang.Override
  public boolean getSquelch() {
    return squelch_;
  }

  public static final int VALIDATORPUBKEY_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString validatorPubKey_;
  /**
   * <pre>
   * validator's public key
   * </pre>
   *
   * <code>required bytes validatorPubKey = 2;</code>
   * @return Whether the validatorPubKey field is set.
   */
  @java.lang.Override
  public boolean hasValidatorPubKey() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * validator's public key
   * </pre>
   *
   * <code>required bytes validatorPubKey = 2;</code>
   * @return The validatorPubKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getValidatorPubKey() {
    return validatorPubKey_;
  }

  public static final int SQUELCHDURATION_FIELD_NUMBER = 3;
  private int squelchDuration_;
  /**
   * <pre>
   * squelch duration in seconds
   * </pre>
   *
   * <code>optional uint32 squelchDuration = 3;</code>
   * @return Whether the squelchDuration field is set.
   */
  @java.lang.Override
  public boolean hasSquelchDuration() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * squelch duration in seconds
   * </pre>
   *
   * <code>optional uint32 squelchDuration = 3;</code>
   * @return The squelchDuration.
   */
  @java.lang.Override
  public int getSquelchDuration() {
    return squelchDuration_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasSquelch()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasValidatorPubKey()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBool(1, squelch_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeBytes(2, validatorPubKey_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeUInt32(3, squelchDuration_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, squelch_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, validatorPubKey_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, squelchDuration_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protocol.TMSquelch)) {
      return super.equals(obj);
    }
    protocol.TMSquelch other = (protocol.TMSquelch) obj;

    if (hasSquelch() != other.hasSquelch()) return false;
    if (hasSquelch()) {
      if (getSquelch()
          != other.getSquelch()) return false;
    }
    if (hasValidatorPubKey() != other.hasValidatorPubKey()) return false;
    if (hasValidatorPubKey()) {
      if (!getValidatorPubKey()
          .equals(other.getValidatorPubKey())) return false;
    }
    if (hasSquelchDuration() != other.hasSquelchDuration()) return false;
    if (hasSquelchDuration()) {
      if (getSquelchDuration()
          != other.getSquelchDuration()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSquelch()) {
      hash = (37 * hash) + SQUELCH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSquelch());
    }
    if (hasValidatorPubKey()) {
      hash = (37 * hash) + VALIDATORPUBKEY_FIELD_NUMBER;
      hash = (53 * hash) + getValidatorPubKey().hashCode();
    }
    if (hasSquelchDuration()) {
      hash = (37 * hash) + SQUELCHDURATION_FIELD_NUMBER;
      hash = (53 * hash) + getSquelchDuration();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protocol.TMSquelch parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol.TMSquelch parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol.TMSquelch parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol.TMSquelch parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol.TMSquelch parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol.TMSquelch parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol.TMSquelch parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protocol.TMSquelch parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protocol.TMSquelch parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protocol.TMSquelch parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protocol.TMSquelch parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protocol.TMSquelch parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protocol.TMSquelch prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protocol.TMSquelch}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol.TMSquelch)
      protocol.TMSquelchOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Ripple.internal_static_protocol_TMSquelch_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Ripple.internal_static_protocol_TMSquelch_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.TMSquelch.class, protocol.TMSquelch.Builder.class);
    }

    // Construct using protocol.TMSquelch.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      squelch_ = false;
      bitField0_ = (bitField0_ & ~0x00000001);
      validatorPubKey_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      squelchDuration_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protocol.Ripple.internal_static_protocol_TMSquelch_descriptor;
    }

    @java.lang.Override
    public protocol.TMSquelch getDefaultInstanceForType() {
      return protocol.TMSquelch.getDefaultInstance();
    }

    @java.lang.Override
    public protocol.TMSquelch build() {
      protocol.TMSquelch result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protocol.TMSquelch buildPartial() {
      protocol.TMSquelch result = new protocol.TMSquelch(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.squelch_ = squelch_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.validatorPubKey_ = validatorPubKey_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.squelchDuration_ = squelchDuration_;
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protocol.TMSquelch) {
        return mergeFrom((protocol.TMSquelch)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protocol.TMSquelch other) {
      if (other == protocol.TMSquelch.getDefaultInstance()) return this;
      if (other.hasSquelch()) {
        setSquelch(other.getSquelch());
      }
      if (other.hasValidatorPubKey()) {
        setValidatorPubKey(other.getValidatorPubKey());
      }
      if (other.hasSquelchDuration()) {
        setSquelchDuration(other.getSquelchDuration());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasSquelch()) {
        return false;
      }
      if (!hasValidatorPubKey()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protocol.TMSquelch parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protocol.TMSquelch) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private boolean squelch_ ;
    /**
     * <pre>
     * squelch if true, otherwise unsquelch
     * </pre>
     *
     * <code>required bool squelch = 1;</code>
     * @return Whether the squelch field is set.
     */
    @java.lang.Override
    public boolean hasSquelch() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * squelch if true, otherwise unsquelch
     * </pre>
     *
     * <code>required bool squelch = 1;</code>
     * @return The squelch.
     */
    @java.lang.Override
    public boolean getSquelch() {
      return squelch_;
    }
    /**
     * <pre>
     * squelch if true, otherwise unsquelch
     * </pre>
     *
     * <code>required bool squelch = 1;</code>
     * @param value The squelch to set.
     * @return This builder for chaining.
     */
    public Builder setSquelch(boolean value) {
      bitField0_ |= 0x00000001;
      squelch_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * squelch if true, otherwise unsquelch
     * </pre>
     *
     * <code>required bool squelch = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSquelch() {
      bitField0_ = (bitField0_ & ~0x00000001);
      squelch_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString validatorPubKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * validator's public key
     * </pre>
     *
     * <code>required bytes validatorPubKey = 2;</code>
     * @return Whether the validatorPubKey field is set.
     */
    @java.lang.Override
    public boolean hasValidatorPubKey() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * validator's public key
     * </pre>
     *
     * <code>required bytes validatorPubKey = 2;</code>
     * @return The validatorPubKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getValidatorPubKey() {
      return validatorPubKey_;
    }
    /**
     * <pre>
     * validator's public key
     * </pre>
     *
     * <code>required bytes validatorPubKey = 2;</code>
     * @param value The validatorPubKey to set.
     * @return This builder for chaining.
     */
    public Builder setValidatorPubKey(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      validatorPubKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * validator's public key
     * </pre>
     *
     * <code>required bytes validatorPubKey = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearValidatorPubKey() {
      bitField0_ = (bitField0_ & ~0x00000002);
      validatorPubKey_ = getDefaultInstance().getValidatorPubKey();
      onChanged();
      return this;
    }

    private int squelchDuration_ ;
    /**
     * <pre>
     * squelch duration in seconds
     * </pre>
     *
     * <code>optional uint32 squelchDuration = 3;</code>
     * @return Whether the squelchDuration field is set.
     */
    @java.lang.Override
    public boolean hasSquelchDuration() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * squelch duration in seconds
     * </pre>
     *
     * <code>optional uint32 squelchDuration = 3;</code>
     * @return The squelchDuration.
     */
    @java.lang.Override
    public int getSquelchDuration() {
      return squelchDuration_;
    }
    /**
     * <pre>
     * squelch duration in seconds
     * </pre>
     *
     * <code>optional uint32 squelchDuration = 3;</code>
     * @param value The squelchDuration to set.
     * @return This builder for chaining.
     */
    public Builder setSquelchDuration(int value) {
      bitField0_ |= 0x00000004;
      squelchDuration_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * squelch duration in seconds
     * </pre>
     *
     * <code>optional uint32 squelchDuration = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSquelchDuration() {
      bitField0_ = (bitField0_ & ~0x00000004);
      squelchDuration_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protocol.TMSquelch)
  }

  // @@protoc_insertion_point(class_scope:protocol.TMSquelch)
  private static final protocol.TMSquelch DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protocol.TMSquelch();
  }

  public static protocol.TMSquelch getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<TMSquelch>
      PARSER = new com.google.protobuf.AbstractParser<TMSquelch>() {
    @java.lang.Override
    public TMSquelch parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TMSquelch(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TMSquelch> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TMSquelch> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protocol.TMSquelch getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

