// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ripple.proto

package protocol;

/**
 * Protobuf type {@code protocol.TMStatusChange}
 */
public final class TMStatusChange extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protocol.TMStatusChange)
    TMStatusChangeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TMStatusChange.newBuilder() to construct.
  private TMStatusChange(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TMStatusChange() {
    newStatus_ = 1;
    newEvent_ = 1;
    ledgerHash_ = com.google.protobuf.ByteString.EMPTY;
    ledgerHashPrevious_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TMStatusChange();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TMStatusChange(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();
              @SuppressWarnings("deprecation")
            protocol.NodeStatus value = protocol.NodeStatus.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(1, rawValue);
            } else {
              bitField0_ |= 0x00000001;
              newStatus_ = rawValue;
            }
            break;
          }
          case 16: {
            int rawValue = input.readEnum();
              @SuppressWarnings("deprecation")
            protocol.NodeEvent value = protocol.NodeEvent.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(2, rawValue);
            } else {
              bitField0_ |= 0x00000002;
              newEvent_ = rawValue;
            }
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            ledgerSeq_ = input.readUInt32();
            break;
          }
          case 34: {
            bitField0_ |= 0x00000008;
            ledgerHash_ = input.readBytes();
            break;
          }
          case 42: {
            bitField0_ |= 0x00000010;
            ledgerHashPrevious_ = input.readBytes();
            break;
          }
          case 48: {
            bitField0_ |= 0x00000020;
            networkTime_ = input.readUInt64();
            break;
          }
          case 56: {
            bitField0_ |= 0x00000040;
            firstSeq_ = input.readUInt32();
            break;
          }
          case 64: {
            bitField0_ |= 0x00000080;
            lastSeq_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protocol.Ripple.internal_static_protocol_TMStatusChange_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protocol.Ripple.internal_static_protocol_TMStatusChange_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protocol.TMStatusChange.class, protocol.TMStatusChange.Builder.class);
  }

  private int bitField0_;
  public static final int NEWSTATUS_FIELD_NUMBER = 1;
  private int newStatus_;
  /**
   * <code>optional .protocol.NodeStatus newStatus = 1;</code>
   * @return Whether the newStatus field is set.
   */
  @java.lang.Override public boolean hasNewStatus() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .protocol.NodeStatus newStatus = 1;</code>
   * @return The newStatus.
   */
  @java.lang.Override public protocol.NodeStatus getNewStatus() {
    @SuppressWarnings("deprecation")
    protocol.NodeStatus result = protocol.NodeStatus.valueOf(newStatus_);
    return result == null ? protocol.NodeStatus.nsCONNECTING : result;
  }

  public static final int NEWEVENT_FIELD_NUMBER = 2;
  private int newEvent_;
  /**
   * <code>optional .protocol.NodeEvent newEvent = 2;</code>
   * @return Whether the newEvent field is set.
   */
  @java.lang.Override public boolean hasNewEvent() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .protocol.NodeEvent newEvent = 2;</code>
   * @return The newEvent.
   */
  @java.lang.Override public protocol.NodeEvent getNewEvent() {
    @SuppressWarnings("deprecation")
    protocol.NodeEvent result = protocol.NodeEvent.valueOf(newEvent_);
    return result == null ? protocol.NodeEvent.neCLOSING_LEDGER : result;
  }

  public static final int LEDGERSEQ_FIELD_NUMBER = 3;
  private int ledgerSeq_;
  /**
   * <code>optional uint32 ledgerSeq = 3;</code>
   * @return Whether the ledgerSeq field is set.
   */
  @java.lang.Override
  public boolean hasLedgerSeq() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional uint32 ledgerSeq = 3;</code>
   * @return The ledgerSeq.
   */
  @java.lang.Override
  public int getLedgerSeq() {
    return ledgerSeq_;
  }

  public static final int LEDGERHASH_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString ledgerHash_;
  /**
   * <code>optional bytes ledgerHash = 4;</code>
   * @return Whether the ledgerHash field is set.
   */
  @java.lang.Override
  public boolean hasLedgerHash() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional bytes ledgerHash = 4;</code>
   * @return The ledgerHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getLedgerHash() {
    return ledgerHash_;
  }

  public static final int LEDGERHASHPREVIOUS_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString ledgerHashPrevious_;
  /**
   * <code>optional bytes ledgerHashPrevious = 5;</code>
   * @return Whether the ledgerHashPrevious field is set.
   */
  @java.lang.Override
  public boolean hasLedgerHashPrevious() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional bytes ledgerHashPrevious = 5;</code>
   * @return The ledgerHashPrevious.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getLedgerHashPrevious() {
    return ledgerHashPrevious_;
  }

  public static final int NETWORKTIME_FIELD_NUMBER = 6;
  private long networkTime_;
  /**
   * <code>optional uint64 networkTime = 6;</code>
   * @return Whether the networkTime field is set.
   */
  @java.lang.Override
  public boolean hasNetworkTime() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional uint64 networkTime = 6;</code>
   * @return The networkTime.
   */
  @java.lang.Override
  public long getNetworkTime() {
    return networkTime_;
  }

  public static final int FIRSTSEQ_FIELD_NUMBER = 7;
  private int firstSeq_;
  /**
   * <code>optional uint32 firstSeq = 7;</code>
   * @return Whether the firstSeq field is set.
   */
  @java.lang.Override
  public boolean hasFirstSeq() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional uint32 firstSeq = 7;</code>
   * @return The firstSeq.
   */
  @java.lang.Override
  public int getFirstSeq() {
    return firstSeq_;
  }

  public static final int LASTSEQ_FIELD_NUMBER = 8;
  private int lastSeq_;
  /**
   * <code>optional uint32 lastSeq = 8;</code>
   * @return Whether the lastSeq field is set.
   */
  @java.lang.Override
  public boolean hasLastSeq() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>optional uint32 lastSeq = 8;</code>
   * @return The lastSeq.
   */
  @java.lang.Override
  public int getLastSeq() {
    return lastSeq_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeEnum(1, newStatus_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeEnum(2, newEvent_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeUInt32(3, ledgerSeq_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeBytes(4, ledgerHash_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeBytes(5, ledgerHashPrevious_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeUInt64(6, networkTime_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeUInt32(7, firstSeq_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      output.writeUInt32(8, lastSeq_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, newStatus_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, newEvent_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, ledgerSeq_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, ledgerHash_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, ledgerHashPrevious_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(6, networkTime_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(7, firstSeq_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(8, lastSeq_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protocol.TMStatusChange)) {
      return super.equals(obj);
    }
    protocol.TMStatusChange other = (protocol.TMStatusChange) obj;

    if (hasNewStatus() != other.hasNewStatus()) return false;
    if (hasNewStatus()) {
      if (newStatus_ != other.newStatus_) return false;
    }
    if (hasNewEvent() != other.hasNewEvent()) return false;
    if (hasNewEvent()) {
      if (newEvent_ != other.newEvent_) return false;
    }
    if (hasLedgerSeq() != other.hasLedgerSeq()) return false;
    if (hasLedgerSeq()) {
      if (getLedgerSeq()
          != other.getLedgerSeq()) return false;
    }
    if (hasLedgerHash() != other.hasLedgerHash()) return false;
    if (hasLedgerHash()) {
      if (!getLedgerHash()
          .equals(other.getLedgerHash())) return false;
    }
    if (hasLedgerHashPrevious() != other.hasLedgerHashPrevious()) return false;
    if (hasLedgerHashPrevious()) {
      if (!getLedgerHashPrevious()
          .equals(other.getLedgerHashPrevious())) return false;
    }
    if (hasNetworkTime() != other.hasNetworkTime()) return false;
    if (hasNetworkTime()) {
      if (getNetworkTime()
          != other.getNetworkTime()) return false;
    }
    if (hasFirstSeq() != other.hasFirstSeq()) return false;
    if (hasFirstSeq()) {
      if (getFirstSeq()
          != other.getFirstSeq()) return false;
    }
    if (hasLastSeq() != other.hasLastSeq()) return false;
    if (hasLastSeq()) {
      if (getLastSeq()
          != other.getLastSeq()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasNewStatus()) {
      hash = (37 * hash) + NEWSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + newStatus_;
    }
    if (hasNewEvent()) {
      hash = (37 * hash) + NEWEVENT_FIELD_NUMBER;
      hash = (53 * hash) + newEvent_;
    }
    if (hasLedgerSeq()) {
      hash = (37 * hash) + LEDGERSEQ_FIELD_NUMBER;
      hash = (53 * hash) + getLedgerSeq();
    }
    if (hasLedgerHash()) {
      hash = (37 * hash) + LEDGERHASH_FIELD_NUMBER;
      hash = (53 * hash) + getLedgerHash().hashCode();
    }
    if (hasLedgerHashPrevious()) {
      hash = (37 * hash) + LEDGERHASHPREVIOUS_FIELD_NUMBER;
      hash = (53 * hash) + getLedgerHashPrevious().hashCode();
    }
    if (hasNetworkTime()) {
      hash = (37 * hash) + NETWORKTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNetworkTime());
    }
    if (hasFirstSeq()) {
      hash = (37 * hash) + FIRSTSEQ_FIELD_NUMBER;
      hash = (53 * hash) + getFirstSeq();
    }
    if (hasLastSeq()) {
      hash = (37 * hash) + LASTSEQ_FIELD_NUMBER;
      hash = (53 * hash) + getLastSeq();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protocol.TMStatusChange parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol.TMStatusChange parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol.TMStatusChange parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol.TMStatusChange parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol.TMStatusChange parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol.TMStatusChange parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol.TMStatusChange parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protocol.TMStatusChange parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protocol.TMStatusChange parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protocol.TMStatusChange parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protocol.TMStatusChange parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protocol.TMStatusChange parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protocol.TMStatusChange prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protocol.TMStatusChange}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol.TMStatusChange)
      protocol.TMStatusChangeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Ripple.internal_static_protocol_TMStatusChange_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Ripple.internal_static_protocol_TMStatusChange_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.TMStatusChange.class, protocol.TMStatusChange.Builder.class);
    }

    // Construct using protocol.TMStatusChange.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      newStatus_ = 1;
      bitField0_ = (bitField0_ & ~0x00000001);
      newEvent_ = 1;
      bitField0_ = (bitField0_ & ~0x00000002);
      ledgerSeq_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      ledgerHash_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      ledgerHashPrevious_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      networkTime_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000020);
      firstSeq_ = 0;
      bitField0_ = (bitField0_ & ~0x00000040);
      lastSeq_ = 0;
      bitField0_ = (bitField0_ & ~0x00000080);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protocol.Ripple.internal_static_protocol_TMStatusChange_descriptor;
    }

    @java.lang.Override
    public protocol.TMStatusChange getDefaultInstanceForType() {
      return protocol.TMStatusChange.getDefaultInstance();
    }

    @java.lang.Override
    public protocol.TMStatusChange build() {
      protocol.TMStatusChange result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protocol.TMStatusChange buildPartial() {
      protocol.TMStatusChange result = new protocol.TMStatusChange(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.newStatus_ = newStatus_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.newEvent_ = newEvent_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.ledgerSeq_ = ledgerSeq_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.ledgerHash_ = ledgerHash_;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        to_bitField0_ |= 0x00000010;
      }
      result.ledgerHashPrevious_ = ledgerHashPrevious_;
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.networkTime_ = networkTime_;
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.firstSeq_ = firstSeq_;
        to_bitField0_ |= 0x00000040;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.lastSeq_ = lastSeq_;
        to_bitField0_ |= 0x00000080;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protocol.TMStatusChange) {
        return mergeFrom((protocol.TMStatusChange)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protocol.TMStatusChange other) {
      if (other == protocol.TMStatusChange.getDefaultInstance()) return this;
      if (other.hasNewStatus()) {
        setNewStatus(other.getNewStatus());
      }
      if (other.hasNewEvent()) {
        setNewEvent(other.getNewEvent());
      }
      if (other.hasLedgerSeq()) {
        setLedgerSeq(other.getLedgerSeq());
      }
      if (other.hasLedgerHash()) {
        setLedgerHash(other.getLedgerHash());
      }
      if (other.hasLedgerHashPrevious()) {
        setLedgerHashPrevious(other.getLedgerHashPrevious());
      }
      if (other.hasNetworkTime()) {
        setNetworkTime(other.getNetworkTime());
      }
      if (other.hasFirstSeq()) {
        setFirstSeq(other.getFirstSeq());
      }
      if (other.hasLastSeq()) {
        setLastSeq(other.getLastSeq());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protocol.TMStatusChange parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protocol.TMStatusChange) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int newStatus_ = 1;
    /**
     * <code>optional .protocol.NodeStatus newStatus = 1;</code>
     * @return Whether the newStatus field is set.
     */
    @java.lang.Override public boolean hasNewStatus() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .protocol.NodeStatus newStatus = 1;</code>
     * @return The newStatus.
     */
    @java.lang.Override
    public protocol.NodeStatus getNewStatus() {
      @SuppressWarnings("deprecation")
      protocol.NodeStatus result = protocol.NodeStatus.valueOf(newStatus_);
      return result == null ? protocol.NodeStatus.nsCONNECTING : result;
    }
    /**
     * <code>optional .protocol.NodeStatus newStatus = 1;</code>
     * @param value The newStatus to set.
     * @return This builder for chaining.
     */
    public Builder setNewStatus(protocol.NodeStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      newStatus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .protocol.NodeStatus newStatus = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNewStatus() {
      bitField0_ = (bitField0_ & ~0x00000001);
      newStatus_ = 1;
      onChanged();
      return this;
    }

    private int newEvent_ = 1;
    /**
     * <code>optional .protocol.NodeEvent newEvent = 2;</code>
     * @return Whether the newEvent field is set.
     */
    @java.lang.Override public boolean hasNewEvent() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .protocol.NodeEvent newEvent = 2;</code>
     * @return The newEvent.
     */
    @java.lang.Override
    public protocol.NodeEvent getNewEvent() {
      @SuppressWarnings("deprecation")
      protocol.NodeEvent result = protocol.NodeEvent.valueOf(newEvent_);
      return result == null ? protocol.NodeEvent.neCLOSING_LEDGER : result;
    }
    /**
     * <code>optional .protocol.NodeEvent newEvent = 2;</code>
     * @param value The newEvent to set.
     * @return This builder for chaining.
     */
    public Builder setNewEvent(protocol.NodeEvent value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      newEvent_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .protocol.NodeEvent newEvent = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNewEvent() {
      bitField0_ = (bitField0_ & ~0x00000002);
      newEvent_ = 1;
      onChanged();
      return this;
    }

    private int ledgerSeq_ ;
    /**
     * <code>optional uint32 ledgerSeq = 3;</code>
     * @return Whether the ledgerSeq field is set.
     */
    @java.lang.Override
    public boolean hasLedgerSeq() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional uint32 ledgerSeq = 3;</code>
     * @return The ledgerSeq.
     */
    @java.lang.Override
    public int getLedgerSeq() {
      return ledgerSeq_;
    }
    /**
     * <code>optional uint32 ledgerSeq = 3;</code>
     * @param value The ledgerSeq to set.
     * @return This builder for chaining.
     */
    public Builder setLedgerSeq(int value) {
      bitField0_ |= 0x00000004;
      ledgerSeq_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 ledgerSeq = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLedgerSeq() {
      bitField0_ = (bitField0_ & ~0x00000004);
      ledgerSeq_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString ledgerHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes ledgerHash = 4;</code>
     * @return Whether the ledgerHash field is set.
     */
    @java.lang.Override
    public boolean hasLedgerHash() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bytes ledgerHash = 4;</code>
     * @return The ledgerHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getLedgerHash() {
      return ledgerHash_;
    }
    /**
     * <code>optional bytes ledgerHash = 4;</code>
     * @param value The ledgerHash to set.
     * @return This builder for chaining.
     */
    public Builder setLedgerHash(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      ledgerHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes ledgerHash = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLedgerHash() {
      bitField0_ = (bitField0_ & ~0x00000008);
      ledgerHash_ = getDefaultInstance().getLedgerHash();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString ledgerHashPrevious_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes ledgerHashPrevious = 5;</code>
     * @return Whether the ledgerHashPrevious field is set.
     */
    @java.lang.Override
    public boolean hasLedgerHashPrevious() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional bytes ledgerHashPrevious = 5;</code>
     * @return The ledgerHashPrevious.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getLedgerHashPrevious() {
      return ledgerHashPrevious_;
    }
    /**
     * <code>optional bytes ledgerHashPrevious = 5;</code>
     * @param value The ledgerHashPrevious to set.
     * @return This builder for chaining.
     */
    public Builder setLedgerHashPrevious(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      ledgerHashPrevious_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes ledgerHashPrevious = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearLedgerHashPrevious() {
      bitField0_ = (bitField0_ & ~0x00000010);
      ledgerHashPrevious_ = getDefaultInstance().getLedgerHashPrevious();
      onChanged();
      return this;
    }

    private long networkTime_ ;
    /**
     * <code>optional uint64 networkTime = 6;</code>
     * @return Whether the networkTime field is set.
     */
    @java.lang.Override
    public boolean hasNetworkTime() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional uint64 networkTime = 6;</code>
     * @return The networkTime.
     */
    @java.lang.Override
    public long getNetworkTime() {
      return networkTime_;
    }
    /**
     * <code>optional uint64 networkTime = 6;</code>
     * @param value The networkTime to set.
     * @return This builder for chaining.
     */
    public Builder setNetworkTime(long value) {
      bitField0_ |= 0x00000020;
      networkTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 networkTime = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearNetworkTime() {
      bitField0_ = (bitField0_ & ~0x00000020);
      networkTime_ = 0L;
      onChanged();
      return this;
    }

    private int firstSeq_ ;
    /**
     * <code>optional uint32 firstSeq = 7;</code>
     * @return Whether the firstSeq field is set.
     */
    @java.lang.Override
    public boolean hasFirstSeq() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional uint32 firstSeq = 7;</code>
     * @return The firstSeq.
     */
    @java.lang.Override
    public int getFirstSeq() {
      return firstSeq_;
    }
    /**
     * <code>optional uint32 firstSeq = 7;</code>
     * @param value The firstSeq to set.
     * @return This builder for chaining.
     */
    public Builder setFirstSeq(int value) {
      bitField0_ |= 0x00000040;
      firstSeq_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 firstSeq = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearFirstSeq() {
      bitField0_ = (bitField0_ & ~0x00000040);
      firstSeq_ = 0;
      onChanged();
      return this;
    }

    private int lastSeq_ ;
    /**
     * <code>optional uint32 lastSeq = 8;</code>
     * @return Whether the lastSeq field is set.
     */
    @java.lang.Override
    public boolean hasLastSeq() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional uint32 lastSeq = 8;</code>
     * @return The lastSeq.
     */
    @java.lang.Override
    public int getLastSeq() {
      return lastSeq_;
    }
    /**
     * <code>optional uint32 lastSeq = 8;</code>
     * @param value The lastSeq to set.
     * @return This builder for chaining.
     */
    public Builder setLastSeq(int value) {
      bitField0_ |= 0x00000080;
      lastSeq_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 lastSeq = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastSeq() {
      bitField0_ = (bitField0_ & ~0x00000080);
      lastSeq_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protocol.TMStatusChange)
  }

  // @@protoc_insertion_point(class_scope:protocol.TMStatusChange)
  private static final protocol.TMStatusChange DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protocol.TMStatusChange();
  }

  public static protocol.TMStatusChange getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<TMStatusChange>
      PARSER = new com.google.protobuf.AbstractParser<TMStatusChange>() {
    @java.lang.Override
    public TMStatusChange parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TMStatusChange(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TMStatusChange> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TMStatusChange> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protocol.TMStatusChange getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

