// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ripple.proto

package protocol;

public interface TMValidatorListCollectionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.TMValidatorListCollection)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required uint32 version = 1;</code>
   * @return Whether the version field is set.
   */
  boolean hasVersion();
  /**
   * <code>required uint32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>required bytes manifest = 2;</code>
   * @return Whether the manifest field is set.
   */
  boolean hasManifest();
  /**
   * <code>required bytes manifest = 2;</code>
   * @return The manifest.
   */
  com.google.protobuf.ByteString getManifest();

  /**
   * <code>repeated .protocol.ValidatorBlobInfo blobs = 3;</code>
   */
  java.util.List<protocol.ValidatorBlobInfo> 
      getBlobsList();
  /**
   * <code>repeated .protocol.ValidatorBlobInfo blobs = 3;</code>
   */
  protocol.ValidatorBlobInfo getBlobs(int index);
  /**
   * <code>repeated .protocol.ValidatorBlobInfo blobs = 3;</code>
   */
  int getBlobsCount();
  /**
   * <code>repeated .protocol.ValidatorBlobInfo blobs = 3;</code>
   */
  java.util.List<? extends protocol.ValidatorBlobInfoOrBuilder> 
      getBlobsOrBuilderList();
  /**
   * <code>repeated .protocol.ValidatorBlobInfo blobs = 3;</code>
   */
  protocol.ValidatorBlobInfoOrBuilder getBlobsOrBuilder(
      int index);
}
