// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ripple.proto

package protocol;

public interface TMValidatorListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.TMValidatorList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required bytes manifest = 1;</code>
   * @return Whether the manifest field is set.
   */
  boolean hasManifest();
  /**
   * <code>required bytes manifest = 1;</code>
   * @return The manifest.
   */
  com.google.protobuf.ByteString getManifest();

  /**
   * <code>required bytes blob = 2;</code>
   * @return Whether the blob field is set.
   */
  boolean hasBlob();
  /**
   * <code>required bytes blob = 2;</code>
   * @return The blob.
   */
  com.google.protobuf.ByteString getBlob();

  /**
   * <code>required bytes signature = 3;</code>
   * @return Whether the signature field is set.
   */
  boolean hasSignature();
  /**
   * <code>required bytes signature = 3;</code>
   * @return The signature.
   */
  com.google.protobuf.ByteString getSignature();

  /**
   * <code>required uint32 version = 4;</code>
   * @return Whether the version field is set.
   */
  boolean hasVersion();
  /**
   * <code>required uint32 version = 4;</code>
   * @return The version.
   */
  int getVersion();
}
