// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ripple.proto

package protocol;

public interface TMValidationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.TMValidation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The serialized validation
   * </pre>
   *
   * <code>required bytes validation = 1;</code>
   * @return Whether the validation field is set.
   */
  boolean hasValidation();
  /**
   * <pre>
   * The serialized validation
   * </pre>
   *
   * <code>required bytes validation = 1;</code>
   * @return The validation.
   */
  com.google.protobuf.ByteString getValidation();

  /**
   * <pre>
   * node vouches signature is correct
   * </pre>
   *
   * <code>optional bool checkedSignature = 2 [deprecated = true];</code>
   * @return Whether the checkedSignature field is set.
   */
  @java.lang.Deprecated boolean hasCheckedSignature();
  /**
   * <pre>
   * node vouches signature is correct
   * </pre>
   *
   * <code>optional bool checkedSignature = 2 [deprecated = true];</code>
   * @return The checkedSignature.
   */
  @java.lang.Deprecated boolean getCheckedSignature();

  /**
   * <pre>
   * Number of hops traveled
   * </pre>
   *
   * <code>optional uint32 hops = 3 [deprecated = true];</code>
   * @return Whether the hops field is set.
   */
  @java.lang.Deprecated boolean hasHops();
  /**
   * <pre>
   * Number of hops traveled
   * </pre>
   *
   * <code>optional uint32 hops = 3 [deprecated = true];</code>
   * @return The hops.
   */
  @java.lang.Deprecated int getHops();
}
